# docker-compose.prod.template.yml (Base)
services:
  $SERVICE_NAME: # TO BE REPLACED WITH THE NAME OF THE SERVICE DURING THE DEPLOY PROCESS
    image: $DOCKER_REGISTRY_IMAGE:$DOCKER_IMMUTABLE_IMAGE_TAG
    restart: always
    healthcheck:
      test: 'curl -f http://localhost/healthcheck || exit 1'
    networks:
      - nginx_reverse_proxy_network
    security_opt:
      - 'no-new-privileges:true'
networks:
  nginx_reverse_proxy_network:
    external: true
