export const SukukStatusList = {
  awaitingIssuerRegistration: 'AwaitingIssuerRegistration',
  termSheetGeneration: 'TermSheetGeneration',
  awaitingIssuerApprovalForTermSheet: 'AwaitingIssuerApprovalForTermSheet',
  preAuctionSetup: 'PreAuctionSetup',
  PreAuctionBidding: 'PreAuctionBidding',
  preAuctionAnalysis: 'PreAuctionAnalysis',
  awaitingIssuerApprovalForSyndication: 'AwaitingIssuerApprovalForSyndication',
  legalReview: 'LegalReview',
  finaliseSyndication: 'FinaliseSyndication',
  bookBuilding: 'BookBuilding',
  auctionSetup: 'AuctionSetup',
  auctionBidding: 'AuctionBidding',
  certificateAllocation: 'CertificateAllocation',
  shariahBoardApproval: 'ShariahBoardApproval',
  bidPayments: 'BidPayments',
  certificateRegistry: 'CertificateRegistry',
  couponPayment: 'CouponPayment',
  redemptionPayment: 'RedemptionPayment',
};

export const SukukStatusArray = [
  'AwaitingIssuerRegistration',
  'TermSheetGeneration',
  'AwaitingIssuerApprovalForTermSheet',
  'PreAuctionSetup',
  'PreAuctionBidding',
  'PreAuctionAnalysis',
  'AwaitingIssuerApprovalForSyndication',
  'LegalReview',
  'FinaliseSyndication',
  'BookBuilding',
  'AuctionSetup',
  'AuctionBidding',
  'CertificateAllocation',
  'ShariahBoardApproval',
  'BidPayments',
  'CertificateRegistry',
  'CouponPayment',
  'RedemptionPayment',
];
