import { Fragment } from "react";
import { useTranslation } from "react-i18next";
import OtpInput from "react-otp-input";
import { useSelector } from "react-redux";

import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import { Form, Formik } from "formik";

import useWethaqAPIParams from "../../../../hooks/useWethaqAPIParams";
import * as authSelectors from "../../../../redux/selectors/auth";
import style from "./style.module.scss";

const ExternalPayment2FA = ({ setSecurityCode }) => {
  const { t } = useTranslation(["auth"]);

  // selectors
  const currentEntityGroup = useSelector(authSelectors.selectCurrentEntityGroup);
  const currentEntityGroupID = currentEntityGroup?.id;

  useWethaqAPIParams({
    currentGroupId: currentEntityGroupID,
  });

  return (
    <Grid container justifyContent="center" alignContent="center">
      <Grid item container direction="column" justifyContent="flex-start" alignContent="center">
        <Formik initialValues={{ otp: "" }} onSubmit={(values) => {}}>
          {({ values, setFieldValue }) => (
            <Form>
              <Box className="my-4">
                {/* <Typography align="center" variant="h6" className="mb-4">
                    {t('auth:Enter Security Code')}
                  </Typography> */}
                <Typography align="center">
                  {t("Enter the security code generated by your two-factor authentication app")}.
                  {t("You will be provided a new security code every 30 seconds")}
                </Typography>
              </Box>
              <Box>
                <OtpInput
                  value={values.otp}
                  onChange={(value) => {
                    setFieldValue("otp", value);
                    setSecurityCode(value);
                  }}
                  isInputNum
                  numInputs={6}
                  shouldAutoFocus
                  renderSeparator={<span>-</span>}
                  renderInput={(props) => <input {...props} />}
                />
              </Box>
            </Form>
          )}
        </Formik>
      </Grid>
    </Grid>
  );
};

export default ExternalPayment2FA;
