export default {
  issuance: {
    privatePlacement: {
      TERMSHEET_GENERATION: "TermSheetGeneration",
      SUBSCRIPTION: "Subscription",
      SUBSCRIPTION_CONFIRMATIONS: "SubscriptionConfirmations",
      SIGNING: "Signing",
      CLOSING: "Closing",
      CERTIFICATE_ALLOCATION: "CertificateAllocation",
      BID_PAYMENTS: "BidPayments",
      CERTIFICATE_REGISTRY: "CertificateRegistry",
      COUPON_PAYMENT: "CouponPayment",
      REDEMPTION_PAYMENT: "RedemptionPayment",
    },
    auction: {
      AWAITING_ISSUER_REGISTRATION: "AwaitingIssuerRegistration",
      TERMSHEET_GENERATION: "TermSheetGeneration",
      AWAITING_ISSUER_APPROVAL_FOR_TERMSHEET: "AwaitingIssuerApprovalForTermSheet",
      PREAUCTION_SETUP: "PreAuctionSetup",
      PREAUCTION_BIDDING: "PreAuctionBidding",
      PREAUCTION_ANALYSIS: "PreAuctionAnalysis",
      AWAITING_ISSUER_APPROVAL_FOR_SYNDICATION: "AwaitingIssuerApprovalForSyndication",
      LEGAL_REVIEW: "LegalReview",
      FINALISE_SYNDICATION: "FinaliseSyndication",
      AUCTION_SETUP: "AuctionSetup",
      AUCTION_BIDDING: "AuctionBidding",
      CERTIFICATE_ALLOCATION: "CertificateAllocation",
      BID_PAYMENTS: "BidPayments",
      CERTIFICATE_REGISTRY: "CertificateRegistry",
      COUPON_PAYMENT: "CouponPayment",
      REDEMPTION_PAYMENT: "RedemptionPayment",
    },
  },
  subscription: {
    SUBSCRIPTION_DEFAULT: "-",
    SUBSCRIPTION_CONFIRMATION_PENDING: "confirmationPending",
    SUBSCRIPTION_CONFIRMED: "confirmed",
  },
  trading: {
    TRADE_STATUS_SUBMITTED: "Submitted",
    TRADE_STATUS_CONFIRMED: "Confirmed",
    TRADE_STATUS_ALLOCATED: "Allocated",
  },
};
