export const ACCOUNTS_FETCH_REQUESTED = "accounts/FETCH_REQUESTED";
export const ACCOUNTS_FETCH_SUCCEEDED = "accounts/FETCH_SUCCEEDED";
export const ACCOUNTS_FETCH_FAILED = "accounts/FETCH_FAILED";

export const ACCOUNTS_ADD_REQUESTED = "accounts/ADD_REQUESTED";
export const ACCOUNTS_ADD_SUCCEEDED = "accounts/ADD_SUCCEEDED";
export const ACCOUNTS_ADD_FAILED = "accounts/ADD_FAILED";

export const ACCOUNTS_EDIT_REQUESTED = "accounts/EDIT_REQUESTED";
export const ACCOUNTS_EDIT_SUCCEEDED = "accounts/EDIT_SUCCEEDED";
export const ACCOUNTS_EDIT_FAILED = "accounts/EDIT_FAILED";

export const ACCOUNTS_DELETE_REQUESTED = "accounts/DELETE_REQUESTED";
export const ACCOUNTS_DELETE_SUCCEEDED = "accounts/DELETE_SUCCEEDED";
export const ACCOUNTS_DELETE_FAILED = "accounts/DELETE_FAILED";

export const PAYMENT_ACCOUNTS_FETCH_REQUESTED = "accounts/payment/FETCH_REQUESTED";
export const PAYMENT_ACCOUNTS_FETCH_SUCCEEDED = "accounts/payment/FETCH_SUCCEEDED";
export const PAYMENT_ACCOUNTS_FETCH_FAILED = "accounts/payments/FETCH_FAILED";

export const PAYMENT_ACCOUNTS_ADD_REQUESTED = "accounts/payment/ADD_REQUESTED";
export const PAYMENT_ACCOUNTS_ADD_SUCCEEDED = "accounts/payment/ADD_SUCCEEDED";
export const PAYMENT_ACCOUNTS_ADD_FAILED = "accounts/payment/ADD_FAILED";

export const PAYMENT_ACCOUNTS_DELETE_REQUESTED = "accounts/payment/DELETE_REQUESTED";
export const PAYMENT_ACCOUNTS_DELETE_SUCCEEDED = "accounts/payment/DELETE_SUCCEEDED";
export const PAYMENT_ACCOUNTS_DELETE_FAILED = "accounts/payment/DELETE_FAILED";

export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_REQUESTED =
  "accounts/payment/SET_AS_DEFAULT_REQUESTED";
export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_SUCCEEDED =
  "accounts/payment/SET_AS_DEFAULT_SUCCEEDED";
export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_FAILED = "accounts/payment/SET_AS_DEFAULT_FAILED";

export const PAYMENT_ACCOUNTS_VALIDATE_REQUESTED = "accounts/payment/VALIDATE_REQUESTED";
export const PAYMENT_ACCOUNTS_VALIDATE_SUCCEEDED = "accounts/payment/VALIDATE_SUCCEEDED";
export const PAYMENT_ACCOUNTS_VALIDATE_FAILED = "accounts/payment/VALIDATE_FAILED";

export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_REQUESTED =
  "accounts/payment/UPLOAD_SUPPORTING_DOC_REQUESTED";
export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_SUCCEEDED =
  "accounts/payment/UPLOAD_SUPPORTING_DOC_SUCCEEDED";
export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_FAILED =
  "accounts/payment/UPLOAD_SUPPORTING_DOC_FAILED";

export const VALIDATED_ACCOUNTS_FETCH_REQUESTED =
  "accounts/paymentAdmin/FETCH_VALIDATED_ACCOUNTS_REQUESTED";
export const VALIDATED_ACCOUNTS_FETCH_SUCCEEDED =
  "accounts/paymentAdmin/FETCH_VALIDATED_ACCOUNTS_SUCCEEDED";
export const VALIDATED_ACCOUNTS_FETCH_FAILED =
  "accounts/paymentAdmin/FETCH_VALIDATED_ACCOUNTS_FAILED";

export const ACCOUNT_FILE_UPLOAD_REQUESTED = "accounts/paymentAdmin/ACCOUNT_FILE_UPLOAD_REQUESTED";
export const ACCOUNT_FILE_UPLOAD_SUCCEEDED = "accounts/paymentAdmin/ACCOUNT_FILE_UPLOAD_SUCCEEDED";
export const ACCOUNT_FILE_UPLOAD_FAILED = "accounts/paymentAdmin/ACCOUNT_FILE_UPLOAD_FAILED";

export const UPDATE_INVESTOR_PAYMENT_REQUESTED =
  "accounts/paymentAdmin/UPDATE_INVESTOR_PAYMENT_REQUESTED";
export const UPDATE_INVESTOR_PAYMENT_SUCCEEDED =
  "accounts/paymentAdmin/UPDATE_INVESTOR_PAYMENT_SUCCEEDED";
export const UPDATE_INVESTOR_PAYMENT_FAILED =
  "accounts/paymentAdmin/UPDATE_INVESTOR_PAYMENT_FAILED";

export const FETCH_INVESTOR_PAYMENT_REQUESTED =
  "accounts/paymentAdmin/FETCH_INVESTOR_PAYMENT_REQUESTED";
export const FETCH_INVESTOR_PAYMENT_SUCCEEDED =
  "accounts/paymentAdmin/FETCH_INVESTOR_PAYMENT_SUCCEEDED";
export const FETCH_INVESTOR_PAYMENT_FAILED = "accounts/paymentAdmin/FETCH_INVESTOR_PAYMENT_FAILED";

export const FETCH_OUTGOING_INSTRUCTIONS_REQUESTED =
  "accounts/payment/FETCH_OUTGOING_INSTRUCTIONS_REQUESTED";
export const FETCH_OUTGOING_INSTRUCTIONS_SUCCEEDED =
  "accounts/payment/FETCH_OUTGOING_INSTRUCTIONS_SUCCEEDED";
export const FETCH_OUTGOING_INSTRUCTIONS_FAILED =
  "accounts/payment/FETCH_OUTGOING_INSTRUCTIONS_FAILED";

export const CREATE_OUTGOING_INSTRUCTIONS_REQUESTED =
  "accounts/payment/CREATE_OUTGOING_INSTRUCTIONS_REQUESTED";
export const CREATE_OUTGOING_INSTRUCTIONS_SUCCEEDED =
  "accounts/payment/CREATE_OUTGOING_INSTRUCTIONS_SUCCEEDED";
export const CREATE_OUTGOING_INSTRUCTIONS_FAILED =
  "accounts/payment/CREATE_OUTGOING_INSTRUCTIONS_FAILED";

export const APPROVE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED =
  "accounts/payment/APPROVE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED";
export const APPROVE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED =
  "accounts/payment/APPROVE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED";
export const APPROVE_OUTGOING_PAYMENT_INSTRUCTION_FAILED =
  "accounts/payment/APPROVE_OUTGOING_PAYMENT_INSTRUCTION_FAILED";

export const FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED =
  "accounts/payment/FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED";
export const FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED =
  "accounts/payment/FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED";
export const FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_FAILED =
  "accounts/payment/FINALIZE_OUTGOING_PAYMENT_INSTRUCTION_FAILED";

export const UPDATE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED =
  "accounts/payment/UPDATE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED";
export const UPDATE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED =
  "accounts/payment/UPDATE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED";
export const UPDATE_OUTGOING_PAYMENT_INSTRUCTION_FAILED =
  "accounts/payment/UPDATE_OUTGOING_PAYMENT_INSTRUCTION_FAILED";

export const CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED =
  "accounts/payment/CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_REQUESTED";
export const CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED =
  "accounts/payment/CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_SUCCEEDED";
export const CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_FAILED =
  "accounts/payment/CLIENT_APPROVE_OUTGOING_PAYMENT_INSTRUCTION_FAILED";

export const PAYMENT_ACCOUNTS_FETCH_RECONCILED_TRANSACTIONS_REQUESTED =
  "accounts/payment/FETCH_RECONCILED_TRANSACTIONS_REQUESTED";
export const PAYMENT_ACCOUNTS_FETCH_RECONCILED_TRANSACTIONS_SUCCEEDED =
  "accounts/payment/FETCH_RECONCILED_TRANSACTIONS_SUCCEEDED";
export const PAYMENT_ACCOUNTS_FETCH_RECONCILED_TRANSACTIONS_FAILED =
  "accounts/payment/FETCH_RECONCILED_TRANSACTIONS_FAILED";
