export const AUTH_RESET_LOGIN_STATE = "auth/LOGIN_RESET_STATE";

export const AUTH_LOGIN_REQUESTED = "auth/LOGIN_REQUESTED";
export const AUTH_LOGIN_SUCCEEDED = "auth/LOGIN_SUCCEEDED";
export const AUTH_LOGIN_MFA_SETUP_FAILED = "auth/LOGIN_MFA_SETUP_FAILED";
export const AUTH_LOGIN_OTP_REQUIRED_FAILED = "auth/LOGIN_OTP_REQUIRED_FAILED";
export const AUTH_LOGIN_FAILED = "auth/LOGIN_FAILED";

export const AUTH_CURRENT_REQUESTED = "AUTH_CURRENT_REQUESTED";
export const AUTH_CURRENT_SUCCEEDED = "AUTH_CURRENT_SUCCEEDED";
export const AUTH_CURRENT_FAILED = "AUTH_CURRENT_FAILED";

export const AUTH_LOGOUT_REQUESTED = "auth/LOGOUT_REQUESTED";
export const AUTH_LOGOUT_SUCCEEDED = "auth/LOGOUT_SUCCEEDED";
export const AUTH_LOGOUT_FAILED = "auth/LOGOUT_FAILED";

export const AUTH_PASSWORD_RESET_LINK_REQUESTED = "auth/PASSWORD_RESET_LINK_REQUESTED";
export const AUTH_PASSWORD_RESET_LINK_SUCCEEDED = "auth/PASSWORD_RESET_LINK_SUCCEEDED";
export const AUTH_PASSWORD_RESET_LINK_FAILED = "auth/PASSWORD_RESET_LINK_FAILED";

export const AUTH_PASSWORD_RESET_REQUESTED = "auth/PASSWORD_RESET_REQUESTED";
export const AUTH_PASSWORD_RESET_SUCCEEDED = "auth/PASSWORD_RESET_SUCCEEDED";
export const AUTH_PASSWORD_RESET_FAILED = "auth/PASSWORD_RESET_FAILED";

export const AUTH_REFRESH_TOKEN_REQUESTED = "auth/REFRESH_TOKEN_REQUESTED";
export const AUTH_REFRESH_TOKEN_SUCCEEDED = "auth/REFRESH_TOKEN_SUCCEEDED";
export const AUTH_REFRESH_TOKEN_FAILED = "auth/REFRESH_TOKEN_FAILED";

export const AUTH_UPDATE_USER_PERMISSION_LIST = "auth/UPDATE_USER_PERMISSION_LIST";

export const INVITE_PLATFORM_USER_REQUESTED = "auth/INVITE_PLATFORM_USER_REQUESTED";
export const INVITE_PLATFORM_USER_SUCCEEDED = "auth/INVITE_PLATFORM_USER_SUCCEEDED";
export const INVITE_PLATFORM_USER_FAILED = "auth/INVITE_PLATFORM_USER_FAILED";

export const REGISTER_ENTITY_USER_REQUESTED = "auth/REGISTER_ENTITY_USER_REQUESTED";
export const REGISTER_ENTITY_USER_SUCCEEDED = "auth/REGISTER_ENTITY_USER_SUCCEEDED";
export const REGISTER_ENTITY_USER_FAILED = "auth/REGISTER_ENTITY_USER_FAILED";

export const FETCH_USER_DATA_REQUESTED = "auth/FETCH_USER_DATA_REQUESTED";
export const FETCH_USER_DATA_SUCCEEDED = "auth/FETCH_USER_DATA_SUCCEEDED";
export const FETCH_USER_DATA_FAILED = "auth/FETCH_USER_DATA_FAILED";

export const DEACTIVATE_USER_REQUESTED = "auth/DEACTIVATE_USER_REQUESTED";
export const DEACTIVATE_USER_SUCCEEDED = "auth/DEACTIVATE_USER_SUCCEEDED";
export const DEACTIVATE_USER_FAILED = "auth/DEACTIVATE_USER_FAILED";

export const UPDATE_USER_REQUESTED = "auth/UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCEEDED = "auth/UPDATE_USER_SUCCEEDED";
export const UPDATE_USER_FAILED = "auth/UPDATE_USER_FAILED";

export const ENTITY_GROUPS_UPDATE_INDEX = "entitygroups/ENTITY_GROUPS_UPDATE_INDEX ";

export const AUTH_MFA_RESET_REQUESTED = "auth/MFA_RESET_REQUESTED";
export const AUTH_MFA_RESET_SUCCEEDED = "auth/MFA_RESET_SUCCEEDED";
export const AUTH_MFA_RESET_FAILED = "auth/MFA_RESET_FAILED";

export const AUTH_PASSWORD_AND_MFA_RESET_REQUESTED = "auth/PASSWORD_AND_MFA_RESET_REQUESTED";
export const AUTH_PASSWORD_AND_MFA_RESET_SUCCEEDED = "auth/PASSWORD_AND_MFA_RESET_SUCCEEDED";
export const AUTH_PASSWORD_AND_MFA_RESET_FAILED = "auth/PASSWORD_AND_MFA_RESET_FAILED";

export const AUTH_CREDS_STATE_RESET_REQUESTED = "auth/AUTH_CREDS_STATE_RESET_REQUESTED";

export const AUTH_FETCH_MFA_PATH_REQUESTED = "auth/MFA_FETCH_PATH_REQUESTED";
export const AUTH_FETCH_MFA_PATH_SUCCEEDED = "auth/MFA_FETCH_PATH_SUCCEEDED";
export const AUTH_FETCH_MFA_PATH_FAILED = "auth/MFA_FETCH_PATH_FAILED";

export const AUTH_SETUP_MFA_REQUESTED = "auth/MFA_SETUP_REQUESTED";
export const AUTH_SETUP_MFA_SUCCEEDED = "auth/MFA_SETUP_SUCCEEDED";
export const AUTH_SETUP_MFA_FAILED = "auth/MFA_SETUP_FAILED";

export const SESSION_TIMEOUT_REQUESTED = "auth/SESSION_TIMEOUT_REQUESTED";
export const SESSION_TIMEOUT_SUCCEEDED = "auth/SESSION_TIMEOUT_SUCCEEDED";

export const ACCESS_DENIED_REQUESTED = "auth/ACCESS_DENIED_REQUESTED";
export const ACCESS_DENIED_SUCCEEDED = "auth/ACCESS_DENIED_SUCCEEDED";
