export const FETCH_TRANSACTIONS_REQUESTED = "billingAndPayments/FETCH_TRANSACTIONS_REQUESTED";
export const FETCH_TRANSACTIONS_SUCCEEDED = "billingAndPayments/FETCH_TRANSACTIONS_SUCCEEDED";
export const FETCH_TRANSACTIONS_FAILED = "billingAndPayments/FETCH_TRANSACTIONS_FAILED";

export const FETCH_ACCOUNTS_REQUESTED = "billingAndPayments/FETCH_ACCOUNTS_REQUESTED";
export const FETCH_ACCOUNTS_SUCCEEDED = "billingAndPayments/FETCH_ACCOUNTS_SUCCEEDED";
export const FETCH_ACCOUNTS_FAILED = "billingAndPayments/FETCH_ACCOUNTS_FAILED";

export const FETCH_SOURCE_OWNERS_REQUESTED = "billingAndPayments/FETCH_SOURCE_OWNERS_REQUESTED";
export const FETCH_SOURCE_OWNERS_SUCCEEDED = "billingAndPayments/FETCH_SOURCE_OWNERS_SUCCEEDED";
export const FETCH_SOURCE_OWNERS_FAILED = "billingAndPayments/FETCH_SOURCE_OWNERS_FAILED";

export const FETCH_EMRGO_OWNERS_REQUESTED = "billingAndPayments/FETCH_EMRGO_OWNERS_REQUESTED";
export const FETCH_EMRGO_OWNERS_SUCCEEDED = "billingAndPayments/FETCH_EMRGO_OWNERS_SUCCEEDED";
export const FETCH_EMRGO_OWNERS_FAILED = "billingAndPayments/FETCH_EMRGO_OWNERS_FAILED";

export const FETCH_DESTINATION_OWNERS_REQUESTED =
  "billingAndPayments/FETCH_DESTINATION_OWNERS_REQUESTED";
export const FETCH_DESTINATION_OWNERS_SUCCEEDED =
  "billingAndPayments/FETCH_DESTINATION_OWNERS_SUCCEEDED";
export const FETCH_DESTINATION_OWNERS_FAILED = "billingAndPayments/FETCH_DESTINATION_OWNERS_FAILED";

export const FETCH_SOURCE_ACCOUNTS_REQUESTED = "billingAndPayments/FETCH_SOURCE_ACCOUNTS_REQUESTED";
export const FETCH_SOURCE_ACCOUNTS_SUCCEEDED = "billingAndPayments/FETCH_SOURCE_ACCOUNTS_SUCCEEDED";
export const FETCH_SOURCE_ACCOUNTS_FAILED = "billingAndPayments/FETCH_SOURCE_ACCOUNTS_FAILED";

export const FETCH_DESTINATION_ACCOUNTS_REQUESTED =
  "billingAndPayments/FETCH_DESTINATION_ACCOUNTS_REQUESTED";
export const FETCH_DESTINATION_ACCOUNTS_SUCCEEDED =
  "billingAndPayments/FETCH_DESTINATION_ACCOUNTS_SUCCEEDED";
export const FETCH_DESTINATION_ACCOUNTS_FAILED =
  "billingAndPayments/FETCH_DESTINATION_ACCOUNTS_FAILED";

export const MONEY_TRANSFER_REQUESTED = "billingAndPayments/MONEY_TRANSFER_REQUESTED";
export const MONEY_TRANSFER_SUCCEEDED = "billingAndPayments/MONEY_TRANSFER_SUCCEEDED";
export const MONEY_TRANSFER_FAILED = "billingAndPayments/MONEY_TRANSFER_FAILED";

export const FETCH_DROPDOWN_VALUES_REQUESTED = "billingAndPayments/FETCH_DROPDOWN_VALUES_REQUESTED";
export const FETCH_DROPDOWN_VALUES_SUCCEEDED = "billingAndPayments/FETCH_DROPDOWN_VALUES_SUCCEEDED";
export const FETCH_DROPDOWN_VALUES_FAILED = "billingAndPayments/FETCH_DROPDOWN_VALUES_FAILED";

export const CREATE_ACCOUNT_REQUESTED = "billingAndPayments/CREATE_ACCOUNT_REQUESTED";
export const CREATE_ACCOUNT_SUCCEEDED = "billingAndPayments/CREATE_ACCOUNT_SUCCEEDED";
export const CREATE_ACCOUNT_FAILED = "billingAndPayments/CREATE_ACCOUNT_FAILED";

export const EDIT_ACCOUNT_REQUESTED = "billingAndPayments/EDIT_ACCOUNT_REQUESTED";
export const EDIT_ACCOUNT_SUCCEEDED = "billingAndPayments/EDIT_ACCOUNT_SUCCEEDED";
export const EDIT_ACCOUNT_FAILED = "billingAndPayments/EDIT_ACCOUNT_FAILED";

export const FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_REQUESTED =
  "billingAndPayments/FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_REQUESTED";
export const FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_SUCCEEDED =
  "billingAndPayments/FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_SUCCEEDED";
export const FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_FAILED =
  "billingAndPayments/FETCH_UNALLOCATED_INCOMING_TRANSACTIONS_FAILED";

export const UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_REQUESTED =
  "billingAndPayments/UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_REQUESTED";
export const UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_SUCCEEDED =
  "billingAndPayments/UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_SUCCEEDED";
export const UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_FAILED =
  "billingAndPayments/UPDATE_UNALLOCATED_INCOMING_TRANSACTIONS_FAILED";

export const RESET_TRANSACTIONS = "billingAndPayments/RESET_TRANSACTIONS";

export const MONEY_TRANSFER_INTERNAL_REQUESTED =
  "billingAndPayments/MONEY_TRANSFER_INTERNAL_REQUESTED";
export const MONEY_TRANSFER_INTERNAL_SUCCEEDED =
  "billingAndPayments/MONEY_TRANSFER_INTERNAL_SUCCEEDED";
export const MONEY_TRANSFER_INTERNAL_FAILED = "billingAndPayments/MONEY_TRANSFER_INTERNAL_FAILED";

export const FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_REQUESTED =
  "billingAndPayments/FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_REQUESTED";
export const FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_SUCCEEDED =
  "billingAndPayments/FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_SUCCEEDED";
export const FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_FAILED =
  "billingAndPayments/FETCH_EXTERNAL_PAYMENTS_AUDIT_DATA_FAILED";

export const RESET_EXTERNAL_PAYMENTS_AUDIT_DATA_REQUESTED =
  "billingAndPayments/RESET_EXTERNAL_PAYMENTS_AUDIT_DATA_REQUESTED";
