export const ENTITIES_REQUESTED = "entities/ENTITIES_REQUESTED";
export const ENTITIES_SUCCEEDED = "entities/ENTITIES_SUCCEEDED";
export const ENTITIES_FAILED = "entities/ENTITIES_FAILED";

export const LEGACY_ENTITIES_REQUESTED = "entities/LEGACY_ENTITIES_REQUESTED";
export const LEGACY_ENTITIES_SUCCEEDED = "entities/LEGACY_ENTITIES_SUCCEEDED";
export const LEGACY_ENTITIES_FAILED = "entities/LEGACY_ENTITIES_FAILED";

export const ENTITY_USERS_REQUESTED = "entities/ENTITY_USERS_REQUESTED";
export const ENTITY_USERS_SUCCEEDED = "entities/ENTITY_USERS_SUCCEEDED";
export const ENTITY_USERS_FAILED = "entities/ENTITY_USERS_FAILED";

export const ADD_PARENT_ENTITY_REQUESTED = "entities/ADD_PARENT_ENTITY_REQUESTED";
export const ADD_PARENT_ENTITY_SUCCEEDED = "entities/ADD_PARENT_ENTITY_SUCCEEDED";
export const ADD_PARENT_ENTITY_FAILED = "entities/ADD_PARENT_ENTITY_FAILED";

export const FETCH_PARENT_ENTITIES_REQUESTED = "entities/FETCH_PARENT_ENTITIES_REQUESTED";
export const FETCH_PARENT_ENTITIES_SUCCEEDED = "entities/FETCH_PARENT_ENTITIES_SUCCEEDED";
export const FETCH_PARENT_ENTITIES_FAILED = "entities/FETCH_PARENT_ENTITIES_FAILED";

export const UPDATE_PARENT_ENTITY_REQUESTED = "entities/UPDATE_PARENT_ENTITY_REQUESTED";
export const UPDATE_PARENT_ENTITY_SUCCEEDED = "entities/UPDATE_PARENT_ENTITY_SUCCEEDED";
export const UPDATE_PARENT_ENTITY_FAILED = "entities/UPDATE_PARENT_ENTITY_FAILED";

export const DEACTIVATE_PARENT_ENTITY_REQUESTED = "entities/DEACTIVATE_PARENT_ENTITY_REQUESTED";
export const DEACTIVATE_PARENT_ENTITY_SUCCEEDED = "entities/DEACTIVATE_PARENT_ENTITY_SUCCEEDED";
export const DEACTIVATE_PARENT_ENTITY_FAILED = "entities/DEACTIVATE_PARENT_ENTITY_FAILED";

export const SET_PARENT_ENTITY_ID_REQUESTED = "entities/SET_PARENT_ENTITY_ID_REQUESTED";
export const SET_PARENT_ENTITY_ID_SUCCEEDED = "entities/SET_PARENT_ENTITY_ID_SUCCEEDED";
export const SET_PARENT_ENTITY_ID_FAILED = "entities/SET_PARENT_ENTITY_ID_FAILED";

export const UPDATE_ENTITY_TYPES_REQUESTED = "entities/UPDATE_ENTITY_TYPES_REQUESTED";
export const UPDATE_ENTITY_TYPES_SUCCEEDED = "entities/UPDATE_ENTITY_TYPES_SUCCEEDED";
export const UPDATE_ENTITY_TYPES_FAILED = "entities/UPDATE_ENTITY_TYPES_FAILED";

export const UPDATE_ENTITY_PREFS_REQUESTED = "entities/UPDATE_ENTITY_PREFS_REQUESTED";
export const UPDATE_ENTITY_PREFS_SUCCEEDED = "entities/UPDATE_ENTITY_PREFS_SUCCEEDED";
export const UPDATE_ENTITY_PREFS_FAILED = "entities/UPDATE_ENTITY_PREFS_FAILED";

export const DEACTIVATE_ENTITY_REQUESTED = "entities/DEACTIVATE_ENTITY_REQUESTED";
export const DEACTIVATE_ENTITY_SUCCEEDED = "entities/DEACTIVATE_ENTITY_SUCCEEDED";
export const DEACTIVATE_ENTITY_FAILED = "entities/DEACTIVATE_ENTITY_FAILED";

export const REACTIVATE_ENTITY_REQUESTED = "entities/REACTIVATE_ENTITY_REQUESTED";
export const REACTIVATE_ENTITY_SUCCEEDED = "entities/REACTIVATE_ENTITY_SUCCEEDED";
export const REACTIVATE_ENTITY_FAILED = "entities/REACTIVATE_ENTITY_FAILED";

export const ENTITY_EDIT_CUSTODY_SETTINGS_REQUESTED = "entities/EDIT_CUSTODY_SETTINGS_REQUESTED";
export const ENTITY_EDIT_CUSTODY_SETTINGS_SUCCEEDED = "entities/EDIT_CUSTODY_SETTINGS_SUCCEEDED";
export const ENTITY_EDIT_CUSTODY_SETTINGS_FAILED = "entities/EDIT_CUSTODY_SETTINGS_FAILED";
