export const FETCH_FORM_REQUESTED = "form/FETCH_FORM_REQUESTED";
export const FETCH_FORM_SUCCEEDED = "form/FETCH_FORM_SUCCEEDED";
export const FETCH_FORM_FAILED = "form/FETCH_FORM_FAILED";
export const POST_FORM_REQUESTED = "form/POST_FORM_REQUESTED";
export const POST_FORM_SUCCESS = "form/POST_FORM_SUCCESS";
