export const ISSUANCES_FETCH_REQUESTED = "issuances/FETCH_REQUESTED";
export const ISSUANCES_FETCH_SUCCEEDED = "issuances/FETCH_SUCCEEDED";
export const ISSUANCES_FETCH_FAILED = "issuances/FETCH_FAILED";

export const ISSUANCE_CREATE_REQUESTED = "issuances/CREATE_REQUESTED";
export const ISSUANCE_CREATE_SUCCEEDED = "issuances/CREATE_SUCCEEDED";
export const ISSUANCE_CREATE_FAILED = "issuances/CREATE_FAILED";

export const ISSUANCE_OVERVIEW_FETCH_REQUESTED = "issuances/OVERVIEW_FETCH_REQUESTED";
export const ISSUANCE_OVERVIEW_FETCH_SUCCEEDED = "issuances/OVERVIEW_FETCH_SUCCEEDED";
export const ISSUANCE_OVERVIEW_FETCH_FAILED = "issuances/OVERVIEW_FETCH_FAILED";

export const ISSUER_CLIENTS_FETCH_REQUESTED = "issuances/issuer_clients/FETCH_REQUESTED";
export const ISSUER_CLIENTS_FETCH_SUCCEEDED = "issuances/issuer_clients/FETCH_SUCCEEDED";
export const ISSUER_CLIENTS_FETCH_FAILED = "issuances/issuer_clients/FETCH_FAILED";

export const CO_ARRANGERS_FETCH_REQUESTED = "issuances/co_arrangers/FETCH_REQUESTED";
export const CO_ARRANGERS_FETCH_SUCCEEDED = "issuances/co_arrangers/FETCH_SUCCEEDED";
export const CO_ARRANGERS_FETCH_FAILED = "issuances/co_arrangers/FETCH_FAILED";

export const FORM_OPTIONS_FETCH_REQUESTED = "issuances/form_options/FETCH_REQUESTED";
export const FORM_OPTIONS_FETCH_SUCCEEDED = "issuances/form_options/FETCH_SUCCEEDED";
export const FORM_OPTIONS_FETCH_FAILED = "issuances/form_options/FETCH_FAILED";

export const ISSUANCE_TERMSHEET_FETCH_REQUESTED = "issuances/termsheet/FETCH_REQUESTED";
export const ISSUANCE_TERMSHEET_FETCH_SUCCEEDED = "issuances/termsheet/FETCH_SUCCEEDED";
export const ISSUANCE_TERMSHEET_FETCH_FAILED = "issuances/termsheet/FETCH_FAILED";

export const ISSUANCE_TERMSHEET_SAVE_REQUESTED = "issuances/termsheet/SAVE_REQUESTED";
export const ISSUANCE_TERMSHEET_SAVE_SUCCEEDED = "issuances/termsheet/SAVE_SUCCEEDED";
export const ISSUANCE_TERMSHEET_SAVE_FAILED = "issuances/termsheet/SAVE_FAILED";

export const ISSUANCE_TERMSHEET_PUBLISH_REQUESTED = "issuances/termsheet/PUBLISH_REQUESTED";
export const ISSUANCE_TERMSHEET_PUBLISH_SUCCEEDED = "issuances/termsheet/PUBLISH_SUCCEEDED";
export const ISSUANCE_TERMSHEET_PUBLISH_FAILED = "issuances/termsheet/PUBLISH_FAILED";

export const ISSUANCE_TERMSHEET_REVIEW_REQUESTED = "issuances/termsheet/REVIEW_REQUESTED";
export const ISSUANCE_TERMSHEET_REVIEW_SUCCEEDED = "issuances/termsheet/REVIEW_SUCCEEDED";
export const ISSUANCE_TERMSHEET_REVIEW__FAILED = "issuances/termsheet/REVIEW_FAILED";

export const ISSUANCE_TERMSHEET_FINALIZE_REQUESTED = "issuances/termsheet/FINALIZE_REQUESTED";
export const ISSUANCE_TERMSHEET_FINALIZE_SUCCEEDED = "issuances/termsheet/FINALIZE_SUCCEEDED";
export const ISSUANCE_TERMSHEET_FINALIZE_FAILED = "issuances/termsheet/FINALIZE_FAILED";

export const ISSUANCE_TERMSHEET_FINAL_TERMS_REQUESTED = "issuances/termsheet/FINAL_TERMS_REQUESTED";
export const ISSUANCE_TERMSHEET_FINAL_TERMS_SUCCEEDED = "issuances/termsheet/FINAL_TERMS_SUCCEEDED";
export const ISSUANCE_TERMSHEET_FINAL_TERMS_FAILED = "issuances/termsheet/FINAL_TERMS_FAILED";

export const ISSUANCE_TERMSHEET_APPROVE_REQUESTED = "issuances/termsheet/APPROVE_REQUESTED";
export const ISSUANCE_TERMSHEET_APPROVE_SUCCEEDED = "issuances/termsheet/APPROVE_SUCCEEDED";
export const ISSUANCE_TERMSHEET_APPROVE_FAILED = "issuances/termsheet/APPROVE_FAILED";

export const UPDATE_SAVE_TERMSHEET_STATE =
  "issuances/termsheet/UPDATE_SAVE_TERMSHEET_STATE_SUCCEEDED";

export const INVESTORS_FETCH_REQUESTED = "issuances/investors/FETCH_REQUESTED";
export const INVESTORS_FETCH_SUCCEEDED = "issuances/investors/FETCH_SUCCEEDED";
export const INVESTORS_FETCH_FAILED = "issuances/investors/FETCH_FAILED";

export const INVESTORS_INVITE_REQUESTED = "issuances/investors/INVITE_REQUESTED";
export const INVESTORS_INVITE_SUCCEEDED = "issuances/investors/INVITE_SUCCEEDED";
export const INVESTORS_INVITE_FAILED = "issuances/investors/INVITE_FAILED";

export const SUBSCRIPTION_SEND_REQUESTED = "issuances/subscription/SEND_REQUESTED";
export const SUBSCRIPTION_SEND_SUCCEEDED = "issuances/subscription/SEND_SUCCEEDED";
export const SUBSCRIPTION_SEND_FAILED = "issuances/subscription/SEND_FAILED";

export const SUBSCRIPTION_FETCH_REQUESTED = "issuances/subscription/FETCH_REQUESTED";
export const SUBSCRIPTION_FETCH_SUCCEEDED = "issuances/subscription/FETCH_SUCCEEDED";
export const SUBSCRIPTION_FETCH_FAILED = "issuances/subscription/FETCH_FAILED";

export const SUBSCRIPTION_CONFIRM_REQUESTED = "issuances/subscription/CONFIRM_REQUESTED";
export const SUBSCRIPTION_CONFIRM_SUCCEEDED = "issuances/subscription/CONFIRM_SUCCEEDED";
export const SUBSCRIPTION_CONFIRM_FAILED = "issuances/subscription/CONFIRM_FAILED";

export const SUBSCRIPTION_FINALISE_REQUESTED = "issuances/subscription/FINALISE_REQUESTED";
export const SUBSCRIPTION_FINALISE_SUCCEEDED = "issuances/subscription/FINALISE_SUCCEEDED";
export const SUBSCRIPTION_FINALISE_FAILED = "issuances/subscription/FINALISE_FAILED";

export const SERVICE_PROVIDER_FETCH_REQUESTED = "issuances/service_provider/FETCH_REQUESTED";
export const SERVICE_PROVIDER_FETCH_SUCCEEDED = "issuances/service_provider/FETCH_SUCCEEDED";
export const SERVICE_PROVIDER_FETCH_FAILED = "issuances/service_provider/FETCH_FAILED";

export const SERVICE_PROVIDER_ENGAGEMENT_REQUESTED =
  "issuances/service_provider/ENGAGEMENT_REQUESTED";
export const SERVICE_PROVIDER_ENGAGEMENT_SUCCEEDED =
  "issuances/service_provider/ENGAGEMENT_SUCCEEDED";
export const SERVICE_PROVIDER_ENGAGEMENT_FAILED = "issuances/service_provider/ENGAGEMENT_FAILED";

export const ENGAGEMENT_REQUESTS_FETCH_REQUESTED = "issuances/engagement_requests/FETCH_REQUESTED";
export const ENGAGEMENT_REQUESTS_FETCH_SUCCEEDED = "issuances/engagement_requests/FETCH_SUCCEEDED";
export const ENGAGEMENT_REQUESTS_FETCH_FAILED = "issuances/engagement_requests/FETCH_FAILED";

export const ENGAGEMENT_LETTER_UPLOAD_REQUESTED = "issuances/engagement_letter/UPLOAD_REQUESTED";
export const ENGAGEMENT_LETTER_UPLOAD_SUCCEEDED = "issuances/engagement_letter/UPLOAD_SUCCEEDED";
export const ENGAGEMENT_LETTER_UPLOAD_FAILED = "issuances/engagement_letter/UPLOAD_FAILED";

export const ENGAGEMENT_LETTER_SIGNATURE_REQUESTED =
  "issuances/engagement_letter/SIGNATURE_REQUESTED";
export const ENGAGEMENT_LETTER_SIGNATURE_SUCCEEDED =
  "issuances/engagement_letter/SIGNATURE_SUCCEEDED";
export const ENGAGEMENT_LETTER_SIGNATURE_FAILED = "issuances/engagement_letter/SIGNATURE_FAILED";

export const ENGAGEMENT_LETTER_URL_FETCH_REQUESTED =
  "issuances/engagement_letter/URL_FETCH_REQUESTED";
export const ENGAGEMENT_LETTER_URL_FETCH_SUCCEEDED =
  "issuances/engagement_letter/URL_FETCH_SUCCEEDED";
export const ENGAGEMENT_LETTER_URL_FETCH_FAILED = "issuances/engagement_letter/URL_FETCH_FAILED";

export const ENGAGEMENT_STATUS_FETCH_REQUESTED = "issuances/engagement_status/FETCH_REQUESTED";
export const ENGAGEMENT_STATUS_FETCH_SUCCEEDED = "issuances/engagement_status/FETCH_SUCCEEDED";
export const ENGAGEMENT_STATUS_FETCH_FAILED = "issuances/engagement_status/FETCH_FAILED";

export const ENGAGEMENT_OBLIGOR_PROPOSAL_FETCH_REQUESTED =
  "issuances/engagement_obligor_proposal/FETCH_REQUESTED";
export const ENGAGEMENT_OBLIGOR_PROPOSAL_FETCH_SUCCEEDED =
  "issuances/engagement_obligor_proposal/FETCH_SUCCEEDED";
export const ENGAGEMENT_OBLIGOR_PROPOSAL_FETCH_FAILED =
  "issuances/engagement_obligor_proposal/FETCH_FAILED";

export const SUBMIT_BYPASS_SIGNED_ENGAGEMENT_REQUESTED =
  "issuances/bypass_signing/SUBMIT_REQUESTED";
export const SUBMIT_BYPASS_SIGNED_ENGAGEMENT_SUCCEEDED =
  "issuances/bypass_signing/SUBMIT_SUCCEEDED";
export const SUBMIT_BYPASS_SIGNED_ENGAGEMENT_FAILED = "issuances/bypass_signing/SUBMIT_FAILED";

export const SIGNING_FETCH_PREACTION_REQUESTED = "issuances/signing/FETCH_PREACTION_REQUESTED";
export const SIGNING_FETCH_PREACTION_SUCCEEDED = "issuances/signing/FETCH_PREACTION_SUCCEEDED";
export const SIGNING_FETCH_PREACTION_FAILED = "issuances/signing/FETCH_PREACTION_FAILED";

export const SIGNING_PREACTION_REQUESTED = "issuances/signing/PREACTION_REQUESTED";
export const SIGNING_PREACTION_SUCCEEDED = "issuances/signing/PREACTION_SUCCEEDED";
export const SIGNING_PREACTION_FAILED = "issuances/signing/PREACTION_FAILED";

export const SIGNING_COMPLETE_AGENDA_REQUESTED = "issuances/signing/COMPLETE_AGENDA_REQUESTED";
export const SIGNING_COMPLETE_AGENDA_SUCCEEDED = "issuances/signing/COMPLETE_AGENDA_SUCCEEDED";
export const SIGNING_COMPLETE_AGENDA_FAILED = "issuances/signing/COMPLETE_AGENDA_FAILED";

export const SIGNING_REVIEW_DOCS_REQUESTED = "issuances/signing/REVIEW_DOCS_REQUESTED";
export const SIGNING_REVIEW_DOCS_SUCCEEDED = "issuances/signing/REVIEW_DOCS_SUCCEEDED";
export const SIGNING_REVIEW_DOCS_FAILED = "issuances/signing/REVIEW_DOCS_FAILED";

export const UPLOAD_EXEC_DOC_REQUESTED = "issuances/signing/UPLOAD_EXEC_DOC_REQUESTED";
export const UPLOAD_EXEC_DOC_SUCCEEDED = "issuances/signing/UPLOAD_EXEC_DOC_SUCCEEDED";
export const UPLOAD_EXEC_DOC_FAILED = "issuances/signing/UPLOAD_EXEC_DOC_FAILED";

export const UPLOAD_REVIEW_DOC_REQUESTED = "issuances/signing/UPLOAD_REVIEW_DOC_REQUESTED";
export const UPLOAD_REVIEW_DOC_SUCCEEDED = "issuances/signing/UPLOAD_REVIEW_DOC_SUCCEEDED";
export const UPLOAD_REVIEW_DOC_FAILED = "issuances/signing/UPLOAD_REVIEW_DOC_FAILED";

export const DOCUSIGN_LINK_REQUESTED = "issuances/signing/DOCUSIGN_LINK_REQUESTED";
export const DOCUSIGN_LINK_SUCCEEDED = "issuances/signing/DOCUSIGN_LINK_SUCCEEDED";
export const DOCUSIGN_LINK_FAILED = "issuances/signing/DOCUSIGN_LINK_FAILED";

export const AUTHLESS_DOCUSIGN_LINK_REQUESTED =
  "issuances/signing/AUTHLESS_DOCUSIGN_LINK_REQUESTED";
export const AUTHLESS_DOCUSIGN_LINK_SUCCEEDED =
  "issuances/signing/AUTHLESS_DOCUSIGN_LINK_SUCCEEDED";
export const AUTHLESS_DOCUSIGN_LINK_FAILED = "issuances/signing/AUTHLESS_DOCUSIGN_LINK_FAILED";

export const REVIEW_DOCUSIGN_LINK_REQUESTED = "issuances/signing/REVIEW_DOCUSIGN_LINK_REQUESTED";
export const REVIEW_DOCUSIGN_LINK_SUCCEEDED = "issuances/signing/REVIEW_DOCUSIGN_LINK_SUCCEEDED";
export const REVIEW_DOCUSIGN_LINK_FAILED = "issuances/signing/REVIEW_DOCUSIGN_LINK_FAILED";

export const COMPLETE_DOCUMENT_REQUESTED = "issuances/signing/COMPLETE_DOCUMENT_REQUESTED";
export const COMPLETE_DOCUMENT_SUCCEEDED = "issuances/signing/COMPLETE_DOCUMENT_SUCCEEDED";
export const COMPLETE_DOCUMENT_FAILED = "issuances/signing/COMPLETE_DOCUMENT_FAILED";

export const SIGNING_AGENDA_REQUESTED = "issuances/signing/AGENDA_REQUESTED";
export const SIGNING_AGENDA_SUCCEEDED = "issuances/signing/AGENDA_SUCCEEDED";
export const SIGNING_AGENDA_FAILED = "issuances/signing/AGENDA_FAILED";
export const SIGNING_POSTACTION_FETCH_REQUESTED = "issuances/signing/POSTACTION_FETCH_REQUESTED";
export const SIGNING_POSTACTION_FETCH_SUCCEEDED = "issuances/signing/POSTACTION_FETCH_SUCCEEDED";
export const SIGNING_POSTACTION_FETCH_FAILED = "issuances/signing/POSTACTION_FETCH_FAILED";

export const SIGNING_POSTACTION_UPDATE_REQUESTED = "issuances/signing/POSTACTION_UPDATE_REQUESTED";
export const SIGNING_POSTACTION_UPDATE_SUCCEEDED = "issuances/signing/POSTACTION_UPDATE_SUCCEEDED";
export const SIGNING_POSTACTION_UPDATE_FAILED = "issuances/signing/POSTACTION_UPDATE_FAILED";

export const CLOSING_DATA_REQUESTED = "issuances/signing/CLOSING_DATA_REQUESTED";
export const CLOSING_DATA_SUCCEEDED = "issuances/signing/CLOSING_DATA_SUCCEEDED";
export const CLOSING_DATA_FAILED = "issuances/signing/CLOSING_DATA_FAILED";

export const CLOSING_REQUEST_REQUESTED = "issuances/signing/CLOSING_REQUEST_REQUESTED";
export const CLOSING_REQUEST_SUCCEEDED = "issuances/signing/CLOSING_REQUEST_SUCCEEDED";
export const CLOSING_REQUEST_FAILED = "issuances/signing/CLOSING_REQUEST_FAILED";

export const CLOSING_CONFIRMATION_REQUESTED = "issuances/signing/CLOSING_CONFIRMATION_REQUESTED";
export const CLOSING_CONFIRMATION_SUCCEEDED = "issuances/signing/CLOSING_CONFIRMATION_SUCCEEDED";
export const CLOSING_CONFIRMATION_FAILED = "issuances/signing/CLOSING_CONFIRMATION_FAILED";

export const CLOSING_INITIALIZATION_REQUESTED =
  "issuances/signing/CLOSING_INITIALIZATION_REQUESTED";
export const CLOSING_INITIALIZATION_SUCCEEDED =
  "issuances/signing/CLOSING_INITIALIZATION_SUCCEEDED";
export const CLOSING_INITIALIZATION_FAILED = "issuances/signing/CLOSING_INITIALIZATION_FAILED";

export const CLOSING_COMPLETE_REQUESTED = "issuances/signing/CLOSING_COMPLETE_REQUESTED";
export const CLOSING_COMPLETE_SUCCEEDED = "issuances/signing/CLOSING_COMPLETE_SUCCEEDED";
export const CLOSING_COMPLETE_FAILED = "issuances/signing/CLOSING_COMPLETE_FAILED";

export const SEND_EXEC_DOC_REQUESTED = "issuances/signing/SEND_EXEC_DOC_REQUESTED";
export const SEND_EXEC_DOC_SUCCEEDED = "issuances/signing/SEND_EXEC_DOC_SUCCEEDED";
export const SEND_EXEC_DOC_FAILED = "issuances/signing/SEND_EXEC_DOC_FAILED";

export const SEND_REVIEW_DOC_REQUESTED = "issuances/signing/SEND_REVIEW_DOC_REQUESTED";
export const SEND_REVIEW_DOC_SUCCEEDED = "issuances/signing/SEND_REVIEW_DOC_SUCCEEDED";
export const SEND_REVIEW_DOC_FAILED = "issuances/signing/SEND_REVIEW_DOC_FAILED";

export const ISSUERS_FETCH_REQUESTED = "issuances/issuers/FETCH_REQUESTED";
export const ISSUERS_FETCH_SUCCEEDED = "issuances/issuers/FETCH_SUCCEEDED";
export const ISSUERS_FETCH_FAILED = "issuances/issuers/FETCH_FAILED";

export const FETCH_CMA_DOCS_REQUESTED = "issuances/cma/FETCH_CMA_DOCS_REQUESTED";
export const FETCH_CMA_DOCS_SUCCEEDED = "issuances/cma/FETCH_CMA_DOCS_SUCCEEDED";
export const FETCH_CMA_DOCS_FAILED = "issuances/cma/FETCH_CMA_DOCS_FAILED";

export const FETCH_CMA_ISSUANCE_APPROVAL_STATUS_REQUESTED =
  "issuances/cma/FETCH_ISSUANCE_APPROVAL_STATUS_REQUESTED";
export const FETCH_CMA_ISSUANCE_APPROVAL_STATUS_SUCCEEDED =
  "issuances/cma/FETCH_ISSUANCE_APPROVAL_STATUS_SUCCEEDED";
export const FETCH_CMA_ISSUANCE_APPROVAL_STATUS_FAILED =
  "issuances/cma/FETCH_ISSUANCE_APPROVAL_STATUS_FAILED";

export const FETCH_CMA_SPE_INCORPORATION_APPROVAL_STATUS_REQUESTED =
  "issuances/cma/FETCH_SPE_INCORPORATION_APPROVAL_STATUS_REQUESTED";
export const FETCH_CMA_SPE_INCORPORATION_APPROVAL_STATUS_SUCCEEDED =
  "issuances/cma/FETCH_SPE_INCORPORATION_APPROVAL_STATUS_SUCCEEDED";
export const FETCH_CMA_SPE_INCORPORATION_APPROVAL_STATUS_FAILED =
  "issuances/cma/FETCH_SPE_INCORPORATION_APPROVAL_STATUS_FAILED";

export const CONFIRM_CMA_ISSUANCE_APPROVAL_STATUS_REQUESTED =
  "issuances/cma/CONFIRM_ISSUANCE_APPROVAL_STATUS_REQUESTED";
export const CONFIRM_CMA_ISSUANCE_APPROVAL_STATUS_SUCCEEDED =
  "issuances/cma/CONFIRM_ISSUANCE_APPROVAL_STATUS_SUCCEEDED";
export const CONFIRM_CMA_ISSUANCE_APPROVAL_STATUS_FAILED =
  "issuances/cma/CONFIRM_ISSUANCE_APPROVAL_STATUS_FAILED";

export const CONFIRM_CMA_SPE_INCORPORATION_APPROVAL_STATUS_REQUESTED =
  "issuances/cma/CONFIRM_SPE_INCORPORATION_APPROVAL_STATUS_REQUESTED";
export const CONFIRM_CMA_SPE_INCORPORATION_APPROVAL_STATUS_SUCCEEDED =
  "issuances/cma/CONFIRM_SPE_INCORPORATION_APPROVAL_STATUS_SUCCEEDED";
export const CONFIRM_CMA_SPE_INCORPORATION_APPROVAL_STATUS_FAILED =
  "issuances/cma/CONFIRM_SPE_INCORPORATION_APPROVAL_STATUS_FAILED";

export const UPLOAD_CMA_RELATED_DOC_REQUESTED = "issuances/cma/UPLOAD_CMA_RELATED_DOC_REQUESTED";
export const UPLOAD_CMA_RELATED_DOC_SUCCEEDED = "issuances/cma/UPLOAD_CMA_RELATED_DOC_SUCCEEDED";
export const UPLOAD_CMA_RELATED_DOC_FAILED = "issuances/cma/UPLOAD_CMA_RELATED_DOC_FAILED";

export const ISSUANCES_FETCH_ALL_REQUESTED = "issuances/FETCH_ALL_REQUESTED";
export const ISSUANCES_FETCH_ALL_SUCCEEDED = "issuances/FETCH_ALL_SUCCEEDED";
export const ISSUANCES_FETCH_ALL_FAILED = "issuances/FETCH_ALL_FAILED";

export const RESET_CMA_DOCUMENT_URLS_STATE = "issuances/RESET_CMA_DOCUMENT_URLS_STATE";

// NEW GET SUKUK BY STATUS QUERY PARAM ENDPOINT URL
export const ISSUANCES_FETCH_BY_STATUS_REQUESTED = "issuances/FETCH_BY_STATUS_REQUESTED";
export const ISSUANCES_FETCH_BY_STATUS_SUCCEEDED = "issuances/FETCH_BY_STATUS_SUCCEEDED";
export const ISSUANCES_FETCH_BY_STATUS_FAILED = "issuances/FETCH_BY_STATUS_FAILED";

export const ADMISSION_TERMSHEET_DATA_REQUESTED = "issuances/admission/TERMSHEET_DATA_REQUESTED";
export const ADMISSION_TERMSHEET_DATA_SUCCEEDED = "issuances/admission/TERMSHEET_DATA_SUCCEEDED";
export const ADMISSION_TERMSHEET_DATA_FAILED = "issuances/admission/TERMSHEET_DATA_FAILED";

export const ADMISSION_TERMS_REQUESTED = "issuances/admission/TERMS_REQUESTED";
export const ADMISSION_TERMS_SUCCEEDED = "issuances/admission/TERMS_SUCCEEDED";
export const ADMISSION_TERMS_FAILED = "issuances/admission/TERMS_FAILED";

export const ADMISSION_SET_TERMS_OBJECT_URL = "issuances/admission/SET_TERMS_OBJECT_URL";
export const ADMISSION_CLEAR_TERMS_OBJECT_URL = "issuances/admission/CLEAR_TERMS_OBJECT_URL";

export const SUBMIT_ADMISSION_TERMS_REQUESTED = "issuances/admission/SUBMIT_TERMS_REQUESTED";
export const SUBMIT_ADMISSION_TERMS_SUCCEEDED = "issuances/admission/SUBMIT_TERMS_SUCCEEDED";
export const SUBMIT_ADMISSION_TERMS_FAILED = "issuances/admission/SUBMIT_TERMS_FAILED";

export const FETCH_ADMISSION_STATUS_REQUESTED = "issuances/admission/ADMISSION_STATUS_REQUESTED";
export const FETCH_ADMISSION_STATUS_SUCCEEDED = "issuances/admission/ADMISSION_STATUS_SUCCEEDED";
export const FETCH_ADMISSION_STATUS_FAILED = "issuances/admission/ADMISSION_STATUS_FAILED";

export const ADD_CO_ARRANGER_REQUESTED = "issuances/co_arranger/ADD_CO_ARRANGER_REQUESTED";
export const ADD_CO_ARRANGER_SUCCEEDED = "issuances/co_arranger/ADD_CO_ARRANGER_SUCCEEDED";
export const ADD_CO_ARRANGER_FAILED = "issuances/co_arranger/ADD_CO_ARRANGER_FAILED";

export const ISSUANCE_TERMSHEET_RESET_REQUESTED = "issuances/termsheet/RESET_REQUESTED";
