
export const CREATE_ACCOUNT_REQUESTED = "safekeeping/CREATE_ACCOUNT_REQUESTED";
export const CREATE_ACCOUNT_SUCCEEDED = "safekeeping/CREATE_ACCOUNT_SUCCEEDED";
export const CREATE_ACCOUNT_FAILED = "safekeeping/CREATE_ACCOUNT_FAILED";

export const READ_ACCOUNTS_REQUESTED = "safekeeping/READ_ACCOUNTS_REQUESTED";
export const READ_ACCOUNTS_SUCCEEDED = "safekeeping/READ_ACCOUNTS_SUCCEEDED";
export const READ_ACCOUNTS_FAILED = "safekeeping/READ_ACCOUNTS_FAILED";

export const UPDATE_ACCOUNT_REQUESTED = "safekeeping/UPDATE_ACCOUNT_REQUESTED";
export const UPDATE_ACCOUNT_SUCCEEDED = "safekeeping/UPDATE_ACCOUNT_SUCCEEDED";
export const UPDATE_ACCOUNT_FAILED = "safekeeping/UPDATE_ACCOUNT_FAILED";

export const READ_ACCOUNT_AUDIT_LOGS_REQUESTED = "safekeeping/READ_ACCOUNT_AUDIT_LOGS_REQUESTED";
export const READ_ACCOUNT_AUDIT_LOGS_SUCCEEDED = "safekeeping/READ_ACCOUNT_AUDIT_LOGS_SUCCEEDED";
export const READ_ACCOUNT_AUDIT_LOGS_FAILED = "safekeeping/READ_ACCOUNT_AUDIT_LOGS_FAILED";