export const SUKUK_OVERVIEW_DATA_REQUESTED = "SUKUK_OVERVIEW_DATA_REQUESTED";
export const SUKUK_OVERVIEW_DATA_SUCCEEDED = "SUKUK_OVERVIEW_DATA_SUCCEEDED";
export const SUKUK_OVERVIEW_DATA_FAILED = "SUKUK_OVERVIEW_DATA_FAILED";
export const SUKUK_OVERVIEW_DATA_RESET_REQUESTED = "SUKUK_OVERVIEW_DATA_RESET_REQUESTED";

export const SUKUK_PROJECT_SETUP_REQUESTED = "SUKUK_PROJECT_SETUP_REQUESTED";
export const SUKUK_PROJECT_SETUP_SUCCEEDED = "SUKUK_PROJECT_SETUP_SUCCEEDED";
export const SUKUK_PROJECT_SETUP_FAILED = "SUKUK_PROJECT_SETUP_FAILED";
