export const SUBMIT_ISSUANCE_FOR_ADMISSION_REQUESTED = "admission/SUBMIT_REQUESTED";
export const SUBMIT_ISSUANCE_FOR_ADMISSION_SUCCEEDED = "admission/SUBMIT_SUCCEEDED";
export const SUBMIT_ISSUANCE_FOR_ADMISSION_FAILED = "admission/SUBMIT_FAILED";

export const MANAGE_ISSUANCE_REQUESTED = "admission/MANAGE_REQUESTED";
export const MANAGE_ISSUANCE_SUCCEEDED = "admission/MANAGE_SUCCEEDED";
export const MANAGE_ISSUANCE_FAILED = "admission/MANAGE_FAILED";
