export const READ_RATECARDS_REQUESTED = 'billing/READ_RATECARDS_REQUESTED';
export const READ_RATECARDS_SUCCEEDED = 'billing/READ_RATECARDS_SUCCEEDED';
export const READ_RATECARDS_FAILED = 'billing/READ_RATECARDS_FAILED';

export const CREATE_RATECARD_REQUESTED = 'billing/CREATE_RATECARD_REQUESTED';
export const CREATE_RATECARD_SUCCEEDED = 'billing/CREATE_RATECARD_SUCCEEDED';
export const CREATE_RATECARD_FAILED = 'billing/CREATE_RATECARD_FAILED';

export const READ_RATECARD_REQUESTED = 'billing/READ_RATECARD_REQUESTED';
export const READ_RATECARD_SUCCEEDED = 'billing/READ_RATECARD_SUCCEEDED';
export const READ_RATECARD_FAILED = 'billing/READ_RATECARD_FAILED';

export const UPDATE_RATECARD_REQUESTED = 'billing/UPDATE_RATECARD_REQUESTED';
export const UPDATE_RATECARD_SUCCEEDED = 'billing/UPDATE_RATECARD_SUCCEEDED';
export const UPDATE_RATECARD_FAILED = 'billing/UPDATE_RATECARD_FAILED';

export const APPROVE_RATECARD_REQUESTED = 'billing/APPROVE_RATECARD_REQUESTED';
export const APPROVE_RATECARD_SUCCEEDED = 'billing/APPROVE_RATECARD_SUCCEEDED';
export const APPROVE_RATECARD_FAILED = 'billing/APPROVE_RATECARD_FAILED';

// INVOICES
export const READ_INVOICES_REQUESTED = 'billing/READ_INVOICES_REQUESTED';
export const READ_INVOICES_SUCCEEDED = 'billing/READ_INVOICES_SUCCEEDED';
export const READ_INVOICES_FAILED = 'billing/READ_INVOICES_FAILED';

export const READ_INVOICE_REQUESTED = 'billing/READ_INVOICE_REQUESTED';
export const READ_INVOICE_SUCCEEDED = 'billing/READ_INVOICE_SUCCEEDED';
export const READ_INVOICE_FAILED = 'billing/READ_INVOICE_FAILED';

export const CALCULATE_INVOICE_REQUESTED = 'billing/CALCULATE_INVOICE_REQUESTED';
export const CALCULATE_INVOICE_SUCCEEDED = 'billing/CALCULATE_INVOICE_SUCCEEDED';
export const CALCULATE_INVOICE_FAILED = 'billing/CALCULATE_INVOICE_FAILED';
export const CALCULATE_INVOICE_RESET = 'billing/CALCULATE_INVOICE_RESET';

export const UPDATE_INVOICE_REQUESTED = 'billing/UPDATE_INVOICE_REQUESTED';
export const UPDATE_INVOICE_SUCCEEDED = 'billing/UPDATE_INVOICE_SUCCEEDED';
export const UPDATE_INVOICE_FAILED = 'billing/UPDATE_INVOICE_FAILED';

export const APPROVE_INVOICE_REQUESTED = 'billing/APPROVE_INVOICE_REQUESTED';
export const APPROVE_INVOICE_SUCCEEDED = 'billing/APPROVE_INVOICE_SUCCEEDED';
export const APPROVE_INVOICE_FAILED = 'billing/APPROVE_INVOICE_FAILED';
