
export const READ_DROPDOWN_REQUESTED = 'bulletins/READ_DROPDOWN_REQUESTED';
export const READ_DROPDOWN_SUCCEEDED = 'bulletins/READ_DROPDOWN_SUCCEEDED';
export const READ_DROPDOWN_FAILED = 'bulletins/READ_DROPDOWN_FAILED';

export const BULLETIN_FETCH_REQUESTED = 'bulletins/BULLETIN_FETCH_REQUESTED';
export const BULLETIN_FETCH_SUCCEEDED = 'bulletins/BULLETIN_FETCH_SUCCEEDED';
export const BULLETIN_FETCH_FAILED = 'bulletins/BULLETIN_FETCH_FAILED';

export const BULLETIN_FILE_UPLOAD_REQUESTED = 'bulletins/BULLETIN_FILE_UPLOAD_REQUESTED';
export const BULLETIN_FILE_UPLOAD_SUCCEEDED = 'bulletins/BULLETIN_FILE_UPLOAD_SUCCEEDED';
export const BULLETIN_FILE_UPLOAD_FAILED = 'bulletins/BULLETIN_FILE_UPLOAD_FAILED';

export const BULLETIN_DOCUMENT_FETCH_REQUESTED = 'bulletins/BULLETIN_DOCUMENT_FETCH_REQUESTED';
export const BULLETIN_DOCUMENT_FETCH_SUCCEEDED = 'bulletins/BULLETIN_DOCUMENT_FETCH_SUCCEEDED';
export const BULLETIN_DOCUMENT_FETCH_FAILED = 'bulletins/BULLETIN_DOCUMENT_FETCH_FAILED';

export const BULLETIN_CREATE_REQUESTED = 'bulletins/BULLETIN_CREATE_REQUESTED';
export const BULLETIN_CREATE_SUCCEEDED = 'bulletins/BULLETIN_CREATE_SUCCEEDED';
export const BULLETIN_CREATE_FAILED = 'bulletins/BULLETIN_CREATE_FAILED';

export const BULLETIN_UPDATE_REQUESTED = 'bulletins/BULLETIN_UPDATE_REQUESTED';
export const BULLETIN_UPDATE_SUCCEEDED = 'bulletins/BULLETIN_UPDATE_SUCCEEDED';
export const BULLETIN_UPDATE_FAILED = 'bulletins/BULLETIN_UPDATE_FAILED';

export const BULLETIN_DELETE_REQUESTED = 'bulletins/BULLETIN_DELETE_REQUESTED';
export const BULLETIN_DELETE_SUCCEEDED = 'bulletins/BULLETIN_DELETE_SUCCEEDED';
export const BULLETIN_DELETE_FAILED = 'bulletins/BULLETIN_DELETE_FAILED';
