export const FETCH_TERMS_REQUESTED = 'clientTerms/FETCH_TERMS_REQUESTED';
export const FETCH_TERMS_SUCCEEDED = 'clientTerms/FETCH_TERMS_SUCCEEDED';
export const FETCH_TERMS_FAILED = 'clientTerms/FETCH_TERMS_FAILED';

export const FETCH_INSTRUCTIONS_REQUESTED = 'clientTerms/FETCH_INSTRUCTIONS_REQUESTED';
export const FETCH_INSTRUCTIONS_SUCCEEDED = 'clientTerms/FETCH_INSTRUCTIONS_SUCCEEDED';
export const FETCH_INSTRUCTIONS_FAILED = 'clientTerms/FETCH_INSTRUCTIONS_FAILED';

export const FETCH_W8BEN_REQUESTED = 'clientTerms/FETCH_W8BEN_REQUESTED';
export const FETCH_W8BEN_SUCCEEDED = 'clientTerms/FETCH_W8BEN_SUCCEEDED';
export const FETCH_W8BEN_FAILED = 'clientTerms/FETCH_W8BEN_FAILED';

export const FETCH_BOARD_RESOLUTION_SAMPLE_REQUESTED = 'clientTerms/FETCH_BOARD_RESOLUTION_SAMPLE_REQUESTED';
export const FETCH_BOARD_RESOLUTION_SAMPLE_SUCCEEDED = 'clientTerms/FETCH_BOARD_RESOLUTION_SAMPLE_SUCCEEDED';
export const FETCH_BOARD_RESOLUTION_SAMPLE_FAILED = 'clientTerms/FETCH_BOARD_RESOLUTION_SAMPLE_FAILED';

export const SUBMIT_TERMS_REQUESTED = 'clientTerms/SUBMIT_TERMS_REQUESTED';
export const SUBMIT_TERMS_SUCCEEDED = 'clientTerms/SUBMIT_TERMS_SUCCEEDED';
export const SUBMIT_TERMS_FAILED = 'clientTerms/SUBMIT_TERMS_FAILED';

export const UPLOAD_FILE_REQUESTED = 'clientTerms/UPLOAD_FILE_REQUESTED';
export const UPLOAD_FILE_SUCCEEDED = 'clientTerms/UPLOAD_FILE_SUCCEEDED';
export const UPLOAD_FILE_FAILED = 'clientTerms/UPLOAD_FILE_FAILED';

export const FETCH_UPLOADED_FILES_REQUESTED = 'clientTerms/FETCH_UPLOADED_FILES_REQUESTED';
export const FETCH_UPLOADED_FILES_SUCCEEDED = 'clientTerms/FETCH_UPLOADED_FILES_SUCCEEDED';
export const FETCH_UPLOADED_FILES_FAILED = 'clientTerms/FETCH_UPLOADED_FILES_FAILED';

export const SUBMIT_VERIFY_TERMS_REQUESTED = 'clientTerms/SUBMIT_VERIFY_TERMS_REQUESTED';
export const SUBMIT_VERIFY_TERMS_SUCCEEDED = 'clientTerms/SUBMIT_VERIFY_TERMS_SUCCEEDED';
export const SUBMIT_VERIFY_TERMS_FAILED = 'clientTerms/SUBMIT_VERIFY_TERMS_FAILED';
