export const CA_EVENTS_FETCH_REQUESTED = "CAEvents/FETCH_REQUESTED";
export const CA_EVENTS_FETCH_SUCCEEDED = "CAEvents/FETCH_SUCCEEDED";
export const CA_EVENTS_FETCH_FAILED = "CAEvents/FETCH_FAILED";

export const CA_EVENT_CANCEL_REQUESTED = "CAEvents/CANCEL_REQUESTED";
export const CA_EVENT_CANCEL_SUCCEEDED = "CAEvents/CANCEL_SUCCEEDED";
export const CA_EVENT_CANCEL_FAILED = "CAEvents/CANCEL_FAILED";

export const CA_EVENT_ADD_REQUESTED = "CAEvents/ADD_REQUESTED";
export const CA_EVENT_ADD_SUCCEEDED = "CAEvents/ADD_SUCCEEDED";
export const CA_EVENT_ADD_FAILED = "CAEvents/ADD_FAILED";

export const CA_EVENT_EDIT_REQUESTED = "CAEvents/EDIT_REQUESTED";
export const CA_EVENT_EDIT_SUCCEEDED = "CAEvents/EDIT_SUCCEEDED";
export const CA_EVENT_EDIT_FAILED = "CAEvents/EDIT_FAILED";

export const CA_EVENT_CLIENT_RESPONSE_REQUESTED = "CAEvents/CLIENT_RESPONSE_REQUESTED";
export const CA_EVENT_CLIENT_RESPONSE_SUCCEEDED = "CAEvents/CLIENT_RESPONSE_SUCCEEDED";
export const CA_EVENT_CLIENT_RESPONSE_FAILED = "CAEvents/CLIENT_RESPONSE_FAILED";

export const CA_EVENT_FETCH_CA_EVENT_REQUESTED = "CAEvents/FETCH_CA_EVENT_REQUESTED";
export const CA_EVENT_FETCH_CA_EVENT_SUCCEEDED = "CAEvents/FETCH_CA_EVENT_SUCCEEDED";
export const CA_EVENT_FETCH_CA_EVENT_FAILED = "CAEvents/FETCH_CA_EVENT_FAILED";

export const CA_EVENT_RESET_STATE = "CAEvents/CA_EVENT_RESET_STATE";
