export const COUNTERPARTY_LIST_FETCH_REQUESTED = 'counterparty/FETCH_REQUESTED';
export const COUNTERPARTY_LIST_FETCH_SUCCEEDED = 'counterparty/FETCH_SUCCEEDED';
export const COUNTERPARTY_LIST_FETCH_FAILED = 'counterparty/FETCH_FAILED';

export const COUNTERPARTY_ADD_REQUESTED = 'counterparty/ADD_REQUESTED';
export const COUNTERPARTY_ADD_SUCCEEDED = 'counterparty/ADD_SUCCEEDED';
export const COUNTERPARTY_ADD_FAILED = 'counterparty/ADD_FAILED';

export const COUNTERPARTY_EDIT_REQUESTED = 'counterparty/EDIT_REQUESTED';
export const COUNTERPARTY_EDIT_SUCCEEDED = 'counterparty/EDIT_SUCCEEDED';
export const COUNTERPARTY_EDIT_FAILED = 'counterparty/EDIT_FAILED';

export const COUNTERPARTY_DELETE_REQUESTED = 'counterparty/DELETE_REQUESTED';
export const COUNTERPARTY_DELETE_SUCCEEDED = 'counterparty/DELETE_SUCCEEDED';
export const COUNTERPARTY_DELETE_FAILED = 'counterparty/DELETE_FAILED';

export const FETCH_DROPDOWNS = 'counterparty/ssi/FETCH_DROPDOWNS';
export const FETCH_DROPDOWNS_SUCCEEDED = 'counterparty/ssi/FETCH_DROPDOWNS_SUCCEEDED';
export const FETCH_DROPDOWNS_FAILED = 'counterparty/ssi/FETCH_DROPDOWNS_FAILED';

export const COUNTERPARTY_SSI_LIST_FETCH_REQUESTED = 'counterparty/ssi/FETCH_REQUESTED';
export const COUNTERPARTY_SSI_LIST_FETCH_SUCCEEDED = 'counterparty/ssi/FETCH_SUCCEEDED';
export const COUNTERPARTY_SSI_LIST_FETCH_FAILED = 'counterparty/ssi/FETCH_FAILED';

export const COUNTERPARTY_SSI_ADD_REQUESTED = 'counterparty/ssi/ADD_REQUESTED';
export const COUNTERPARTY_SSI_ADD_SUCCEEDED = 'counterparty/ssi/ADD_SUCCEEDED';
export const COUNTERPARTY_SSI_ADD_FAILED = 'counterparty/ssi/ADD_FAILED';

export const COUNTERPARTY_SSI_EDIT_REQUESTED = 'counterparty/ssi/EDIT_REQUESTED';
export const COUNTERPARTY_SSI_EDIT_SUCCEEDED = 'counterparty/ssi/EDIT_SUCCEEDED';
export const COUNTERPARTY_SSI_EDIT_FAILED = 'counterparty/ssi/EDIT_FAILED';

export const COUNTERPARTY_SSI_DELETE_REQUESTED = 'counterparty/ssi/DELETE_REQUESTED';
export const COUNTERPARTY_SSI_DELETE_SUCCEEDED = 'counterparty/ssi/DELETE_SUCCEEDED';
export const COUNTERPARTY_SSI_DELETE_FAILED = 'counterparty/ssi/DELETE_FAILED';
