export const COUPONS_ADD_PAYMENT_SCHEDULE_REQUESTED = "coupons/ADD_PAYMENT_SCHEDULE_REQUESTED";
export const COUPONS_ADD_PAYMENT_SCHEDULE_SUCCEEDED = "coupons/ADD_PAYMENT_SCHEDULE_SUCCEEDED";
export const COUPONS_ADD_PAYMENT_SCHEDULE_FAILED = "coupons/ADD_PAYMENT_SCHEDULE_FAILED";
export const COUPONS_EDIT_PAYMENT_SCHEDULE_REQUESTED = "coupons/EDIT_PAYMENT_SCHEDULE_REQUESTED";
export const COUPONS_EDIT_PAYMENT_SCHEDULE_SUCCEEDED = "coupons/EDIT_PAYMENT_SCHEDULE_SUCCEEDED";
export const COUPONS_EDIT_PAYMENT_SCHEDULE_FAILED = "coupons/EDIT_PAYMENT_SCHEDULE_FAILED";
export const COUPONS_FETCH_ALL_PAYMENT_SCHEDULES_REQUESTED =
  "coupons/FETCH_ALL_PAYMENT_SCHEDULES_REQUESTED";
export const COUPONS_FETCH_ALL_PAYMENT_SCHEDULES_SUCCEEDED =
  "coupons/FETCH_ALL_PAYMENT_SCHEDULES_SUCCEEDED";
export const COUPONS_FETCH_ALL_PAYMENT_SCHEDULES_FAILED =
  "coupons/FETCH_ALL_PAYMENT_SCHEDULES_FAILED";
export const COUPONS_FETCH_PAYMENT_SCHEDULE_BY_ID_REQUESTED =
  "coupons/FETCH_PAYMENT_SCHEDULE_BY_ID_REQUESTED";
export const COUPONS_FETCH_PAYMENT_SCHEDULE_BY_ID_SUCCEEDED =
  "coupons/FETCH_PAYMENT_SCHEDULE_BY_ID_SUCCEEDED";
export const COUPONS_FETCH_PAYMENT_SCHEDULE_BY_ID_FAILED =
  "coupons/FETCH_PAYMENT_SCHEDULE_BY_ID_FAILED";
export const COUPONS_PUBLISH_PAYMENT_SCHEDULE_BY_ID_REQUESTED =
  "coupons/PUBLISH_PAYMENT_SCHEDULE_BY_ID_REQUESTED";
export const COUPONS_PUBLISH_PAYMENT_SCHEDULE_BY_ID_SUCCEEDED =
  "coupons/PUBLISH_PAYMENT_SCHEDULE_BY_ID_SUCCEEDED";
export const COUPONS_PUBLISH_PAYMENT_SCHEDULE_BY_ID_FAILED =
  "coupons/PUBLISH_PAYMENT_SCHEDULE_BY_ID_FAILED";
export const COUPONS_FETCH_ALL_COUPON_EVENTS_REQUESTED =
  "coupons/COUPONS_FETCH_ALL_COUPON_EVENTS_REQUESTED";
export const COUPONS_FETCH_ALL_COUPON_EVENTS_SUCCEEDED =
  "coupons/COUPONS_FETCH_ALL_COUPON_EVENTS_SUCCEEDED";
export const COUPONS_FETCH_ALL_COUPON_EVENTS_FAILED =
  "coupons/COUPONS_FETCH_ALL_COUPON_EVENTS_FAILED";
export const COUPONS_ADD_ALLOCATION_REQUESTED = "coupons/ADD_ALLOCATION_REQUESTED";
export const COUPONS_ADD_ALLOCATION_SUCCEEDED = "coupons/ADD_ALLOCATION_SUCCEEDED";
export const COUPONS_ADD_ALLOCATION_FAILED = "coupons/ADD_ALLOCATION_FAILED";
export const COUPONS_APPROVE_ALLOCATION_REQUESTED = "coupons/APPROVE_ALLOCATION_REQUESTED";
export const COUPONS_APPROVE_ALLOCATION_SUCCEEDED = "coupons/APPROVE_ALLOCATION_SUCCEEDED";
export const COUPONS_APPROVE_ALLOCATION_FAILED = "coupons/APPROVE_ALLOCATION_FAILED";
export const COUPONS_RESET_STATE = "coupons/RESET_STATE";
