export const FETCH_USERS_REQUESTED = "issuances/documents/FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCEEDED = "issuances/documents/FETCH_USERS_SUCCEEDED";
export const FETCH_USERS_FAILED = "issuances/documents/FETCH_USERS_FAILED";

export const FETCH_USER_FILES_REQUESTED = "issuances/documents/FETCH_USER_FILES_REQUESTED";
export const FETCH_USER_FILES_SUCCEEDED = "issuances/documents/FETCH_USER_FILES_SUCCEEDED";
export const FETCH_USER_FILES_FAILED = "issuances/documents/FETCH_USER_FILES_FAILED";

export const UPLOAD_FILE_REQUESTED = "issuances/documents/UPLOAD_FILE_REQUESTED";
export const UPLOAD_FILE_SUCCEEDED = "issuances/documents/UPLOAD_FILE_SUCCEEDED";
export const UPLOAD_FILE_FAILED = "issuances/documents/UPLOAD_FILE_FAILED";

export const PROCESS_FILE_REQUESTED = "issuances/documents/PROCESS_FILE_REQUESTED";
export const PROCESS_FILE_SUCCEEDED = "issuances/documents/PROCESS_FILE_SUCCEEDED";
export const PROCESS_FILE_FAILED = "issuances/documents/PROCESS_FILE_FAILED";

export const DWONLOAD_FILE_REQUESTED = "issuances/documents/DWONLOAD_FILE_REQUESTED";
export const DWONLOAD_FILE_SUCCEEDED = "issuances/documents/DWONLOAD_FILE_SUCCEEDED";
export const DWONLOAD_FILE_FAILED = "issuances/documents/DWONLOAD_FILE_FAILED";

export const PREVIEW_FILE_REQUESTED = "issuances/documents/PREVIEW_FILE_REQUESTED";
export const PREVIEW_FILE_SUCCEEDED = "issuances/documents/PREVIEW_FILE_SUCCEEDED";
export const PREVIEW_FILE_FAILED = "issuances/documents/PREVIEW_FILE_FAILED";

export const FETCH_DOCUSIGN_URL_REQUESTED = "issuances/documents/FETCH_DOCUSIGN_URL_REQUESTED";
export const FETCH_DOCUSIGN_URL_SUCCEEDED = "issuances/documents/FETCH_DOCUSIGN_URL_SUCCEEDED";
export const FETCH_DOCUSIGN_URL_FAILED = "issuances/documents/FETCH_DOCUSIGN_URL_FAILED";

export const UPDATE_DOCUMENT_PERMISSION_REQUESTED =
  "issuances/documents/UPDATE_DOCUMENT_PERMISSION_REQUESTED";
export const UPDATE_DOCUMENT_PERMISSION_SUCCEEDED =
  "issuances/documents/UPDATE_DOCUMENT_PERMISSION_SUCCEEDED";
export const UPDATE_DOCUMENT_PERMISSION_FAILED =
  "issuances/documents/UPDATE_DOCUMENT_PERMISSION_FAILED";

export const DOCUMENT_UPLOAD_REQUEST_REQUESTED =
  "issuances/documents/DOCUMENT_UPLOAD_REQUEST_REQUESTED";
export const DOCUMENT_UPLOAD_REQUEST_SUCCEEDED =
  "issuances/documents/DOCUMENT_UPLOAD_REQUEST_SUCCEEDED";
export const DOCUMENT_UPLOAD_REQUEST_FAILED = "issuances/documents/DOCUMENT_UPLOAD_REQUEST_FAILED";

export const DOCUMENT_MARK_OBTAINED_REQUESTED =
  "issuances/documents/DOCUMENT_MARK_OBTAINED_REQUESTED";
export const DOCUMENT_MARK_OBTAINED_SUCCEEDED =
  "issuances/documents/DOCUMENT_MARK_OBTAINED_SUCCEEDED";
export const DOCUMENT_MARK_OBTAINED_FAILED = "issuances/documents/DOCUMENT_MARK_OBTAINED_FAILED";
