export const FETCH_DROPDOWN_OPTIONS_REQUESTED = 'dropdown/FETCH_DROPDOWN_OPTIONS_REQUESTED';
export const FETCH_DROPDOWN_OPTIONS_SUCCEEDED = 'dropdown/FETCH_DROPDOWN_OPTIONS_SUCCEEDED';
export const FETCH_DROPDOWN_OPTIONS_FAILED = 'dropdown/FETCH_DROPDOWN_OPTIONS_FAILED';
export const RESET_DROPDOWN_STATE = 'dropdown/RESET_DROPDOWN_STATE';
