export const ENTITY_GROUPS_REQUESTED = 'entities/ENTITY_GROUPS_REQUESTED';
export const ENTITY_GROUPS_SUCCEEDED = 'entities/ENTITY_GROUPS_SUCCEEDED';
export const ENTITY_GROUPS_FAILED = 'entities/ENTITY_GROUPS_FAILED';

export const ENTITY_GROUP_DETAILS_REQUESTED = 'entityGroups/ENTITY_GROUP_DETAILS_REQUESTED';
export const ENTITY_GROUP_DETAILS_SUCCEEDED = 'entityGroups/ENTITY_GROUP_DETAILS_SUCCEEDED';
export const ENTITY_GROUP_DETAILS_FAILED = 'entityGroups/ENTITY_GROUP_DETAILS_FAILED';

export const ENTITY_GROUP_USER_ACL_EDIT_REQUESTED = 'entityGroups/ENTITY_GROUP_USER_ACL_EDIT_REQUESTED';
export const ENTITY_GROUP_USER_ACL_EDIT_SUCCEEDED = 'entityGroups/ENTITY_GROUP_USER_ACL_EDIT_SUCCEEDED';
export const ENTITY_GROUP_USER_ACL_EDIT_FAILED = 'entityGroups/ENTITY_GROUP_USER_ACL_EDIT_FAILED';

export const ADD_ENTITY_GROUP_REQUESTED = 'entityGroups/ADD_ENTITY_GROUP_REQUESTED';
export const ADD_ENTITY_GROUP_SUCCEEDED = 'entityGroups/ADD_ENTITY_GROUP_SUCCEEDED';
export const ADD_ENTITY_GROUP_FAILED = 'entityGroups/ADD_ENTITY_GROUP_FAILED';

export const ATTACH_ENTITY_USER_TO_ENTITY_GROUP_REQUESTED = 'entityGroups/ATTACH_ENTITY_USER_TO_ENTITY_GROUP_REQUESTED';
export const ATTACH_ENTITY_USER_TO_ENTITY_GROUP_SUCCEEDED = 'entityGroups/ATTACH_ENTITY_USER_TO_ENTITY_GROUP_SUCCEEDED';
export const ATTACH_ENTITY_USER_TO_ENTITY_GROUP_FAILED = 'entityGroups/ATTACH_ENTITY_USER_TO_ENTITY_GROUP_FAILED';

export const REQUEST_AGREEMENT_REQUESTED = 'entityGroups/REQUEST_AGREEMENT_REQUESTED';
export const REQUEST_AGREEMENT_SUCCEEDED = 'entityGroups/REQUEST_AGREEMENT_SUCCEEDED';
export const REQUEST_AGREEMENT_FAILED = 'entityGroups/REQUEST_AGREEMENT_FAILED';
