export const EXTERNAL_SECURITIES_LIST_FETCH_REQUESTED = 'externalSecurities/FETCH_REQUESTED';
export const EXTERNAL_SECURITIES_LIST_FETCH_SUCCEEDED = 'externalSecurities/FETCH_SUCCEEDED';
export const EXTERNAL_SECURITIES_LIST_FETCH_FAILED = 'externalSecurities/FETCH_FAILED';

export const EXTERNAL_SECURITIES_ADD_REQUESTED = 'externalSecurities/ADD_REQUESTED';
export const EXTERNAL_SECURITIES_ADD_SUCCEEDED = 'externalSecurities/ADD_SUCCEEDED';
export const EXTERNAL_SECURITIES_ADD_FAILED = 'externalSecurities/ADD_FAILED';

export const EXTERNAL_SECURITIES_EDIT_REQUESTED = 'externalSecurities/EDIT_REQUESTED';
export const EXTERNAL_SECURITIES_EDIT_SUCCEEDED = 'externalSecurities/EDIT_SUCCEEDED';
export const EXTERNAL_SECURITIES_EDIT_FAILED = 'externalSecurities/EDIT_FAILED';

export const EXTERNAL_SECURITIES_DELETE_REQUESTED = 'externalSecurities/DELETE_REQUESTED';
export const EXTERNAL_SECURITIES_DELETE_SUCCEEDED = 'externalSecurities/DELETE_SUCCEEDED';
export const EXTERNAL_SECURITIES_DELETE_FAILED = 'externalSecurities/DELETE_FAILED';

export const EXTERNAL_SECURITIES_ADD_EQUITY_REQUESTED = 'externalSecurities/ADD_EQUITY_REQUESTED';
export const EXTERNAL_SECURITIES_ADD_EQUITY_SUCCEEDED = 'externalSecurities/ADD_EQUITY_SUCCEEDED';
export const EXTERNAL_SECURITIES_ADD_EQUITY_FAILED = 'externalSecurities/ADD_EQUITY_FAILED';

export const EXTERNAL_SECURITIES_SEARCH_REQUESTED = 'externalSecurities/SEARCH_REQUESTED';
export const EXTERNAL_SECURITIES_SEARCH_SUCCEEDED = 'externalSecurities/SEARCH_SUCCEEDED';
export const EXTERNAL_SECURITIES_SEARCH_FAILED = 'externalSecurities/SEARCH_FAILED';

export const EXTERNAL_SECURITIES_RESET_SEARCH_RESULTS = 'externalSecurities/RESET_SEARCH_RESULTS';
