export const FX_TRANSACTIONS_FETCH_REQUESTED = 'fxTransactions/FETCH_REQUESTED';
export const FX_TRANSACTIONS_FETCH_SUCCEEDED = 'fxTransactions/FETCH_SUCCEEDED';
export const FX_TRANSACTIONS_FETCH_FAILED = 'fxTransactions/FETCH_FAILED';

export const FX_TRANSACTIONS_ADD_REQUESTED = 'fxTransactions/ADD_REQUESTED';
export const FX_TRANSACTIONS_ADD_SUCCEEDED = 'fxTransactions/ADD_SUCCEEDED';
export const FX_TRANSACTIONS_ADD_FAILED = 'fxTransactions/ADD_FAILED';

export const FX_TRANSACTIONS_PROCESS_REQUESTED = 'fxTransactions/PROCESS_REQUESTED';
export const FX_TRANSACTIONS_PROCESS_SUCCEEDED = 'fxTransactions/PROCESS_SUCCEEDED';
export const FX_TRANSACTIONS_PROCESS_FAILED = 'fxTransactions/PROCESS_FAILED';
