// TODO: REORGANIZE KYC ACTIONS

export const KYC_EOI_SEND_KIT_REQUESTED = 'kyc/eoi/SEND_KIT_REQUESTED';
export const KYC_EOI_SEND_KIT_SUCCEEDED = 'kyc/eoi/SEND_KIT_SUCCEEDED';
export const KYC_EOI_SEND_KIT_FAILED = 'kyc/eoi/SEND_KIT_FAILED';

export const ENTITY_KYC_FETCH_REQUESTED = 'kyc/ENTITY_KYC_FETCH_REQUESTED';
export const ENTITY_KYC_FETCH_SUCCEEDED = 'kyc/ENTITY_KYC_FETCH_SUCCEEDED';
export const ENTITY_KYC_FETCH_FAILED = 'kyc/ENTITY_KYC_FETCH_FAILED';

export const ENTITY_KYC_POST_REQUESTED = 'kyc/ENTITY_KYC_POST_REQUESTED';
export const ENTITY_KYC_POST_SUCCEEDED = 'kyc/ENTITY_KYC_POST_SUCCEEDED';
export const ENTITY_KYC_POST_FAILED = 'kyc/ENTITY_KYC_POST_FAILED';

export const KYC_APPROVAL_REQUESTED = 'kyc/APPROVAL_REQUESTED';
export const KYC_APPROVAL_SUCCEEDED = 'kyc/APPROVAL_SUCCEEDED';
export const KYC_APPROVAL_FAILED = 'kyc/APPROVAL_FAILED';

export const KYC_FILE_UPLOAD_REQUESTED = 'kyc/FILE_UPLOAD_REQUESTED';
export const KYC_FILE_UPLOAD_SUCCEEDED = 'kyc/FILE_UPLOAD_SUCCEEDED';
export const KYC_FILE_UPLOAD_FAILED = 'kyc/FILE_UPLOAD_FAILED';

export const FETCH_CC_DROPDOWNS = 'kyc/FETCH_CC_DROPDOWNS';
export const FETCH_CC_DROPDOWNS_SUCCEEDED = 'kyc/FETCH_CC_DROPDOWNS_SUCCEEDED';
export const FETCH_CC_DROPDOWNS_FAILED = 'kyc/FETCH_CC_DROPDOWNS_FAILED';

export const KYC_CC_DATA_POST_REQUESTED = 'kyc/cc_data/POST_REQUESTED';
export const KYC_CC_DATA_POST_SUCCEEDED = 'kyc/cc_data/POST_SUCCEEDED';
export const KYC_CC_DATA_POST_FAILED = 'kyc/cc_data/POST_FAILED';

export const KYC_REQ_DATA_POST_REQUESTED = 'kyc/req_data/POST_REQUESTED';
export const KYC_REQ_DATA_POST_SUCCEEDED = 'kyc/req_data/POST_SUCCEEDED';
export const KYC_REQ_DATA_POST_FAILED = 'kyc/req_data/POST_FAILED';

export const KYC_SANCTIONS_DATA_POST_REQUESTED = 'kyc/sanctions_data/POST_REQUESTED';
export const KYC_SANCTIONS_DATA_POST_SUCCEEDED = 'kyc/sanctions_data/POST_SUCCEEDED';
export const KYC_SANCTIONS_DATA_POST_FAILED = 'kyc/sanctions_data/POST_FAILED';

export const KYC_SUBMISSION_REQUESTED = 'kyc/SUBMISSION_REQUESTED';
export const KYC_SUBMISSION_SUCCEEDED = 'kyc/SUBMISSION_SUCCEEDED';
export const KYC_SUBMISSION_FAILED = 'kyc/SUBMISSION_FAILED';

export const KYC_REJECTION_REQUESTED = 'kyc/REJECTION_REQUESTED';
export const KYC_REJECTION_SUCCEEDED = 'kyc/REJECTION_SUCCEEDED';
export const KYC_REJECTION_FAILED = 'kyc/REJECTION_FAILED';

export const FETCH_DROPDOWNS = 'kyc/FETCH_DROPDOWNS';
export const FETCH_DROPDOWNS_SUCCEEDED = 'kyc/FETCH_DROPDOWNS_SUCCEEDED';
export const FETCH_DROPDOWNS_FAILED = 'kyc/FETCH_DROPDOWNS_FAILED';

export const RESET_UPLOADED_KYC_FILES_STATE = 'kyc/RESET_UPLOADED_KYC_FILES_STATE';

export const PAYMENT_ACCOUNTS_FETCH_REQUESTED = 'kyc/payment/FETCH_REQUESTED';
export const PAYMENT_ACCOUNTS_FETCH_SUCCEEDED = 'kyc/payment/FETCH_SUCCEEDED';
export const PAYMENT_ACCOUNTS_FETCH_FAILED = 'kyc/payments/FETCH_FAILED';

export const PAYMENT_ACCOUNTS_FETCH_BY_ENTITY_ID_REQUESTED = 'kyc/payment/FETCH_BY_ENTITY_ID_REQUESTED';
export const PAYMENT_ACCOUNTS_FETCH_BY_ENTITY_ID_SUCCEEDED = 'kyc/payment/FETCH_BY_ENTITY_ID_SUCCEEDED';
export const PAYMENT_ACCOUNTS_FETCH_BY_ENTITY_ID_FAILED = 'kyc/payments/FETCH_BY_ENTITY_ID_FAILED';

export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_REQUESTED = 'kyc/payment/UPLOAD_SUPPORTING_DOC_REQUESTED';
export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_SUCCEEDED = 'kyc/payment/UPLOAD_SUPPORTING_DOC_SUCCEEDED';
export const PAYMENT_ACCOUNTS_UPLOAD_SUPPORTING_DOC_FILE_FAILED = 'kyc/payment/UPLOAD_SUPPORTING_DOC_FAILED';

export const PAYMENT_ACCOUNTS_ADD_REQUESTED = 'kyc/payment/ADD_REQUESTED';
export const PAYMENT_ACCOUNTS_ADD_SUCCEEDED = 'kyc/payment/ADD_SUCCEEDED';
export const PAYMENT_ACCOUNTS_ADD_FAILED = 'kyc/payment/ADD_FAILED';

export const PAYMENT_ACCOUNTS_DELETE_REQUESTED = 'kyc/payment/DELETE_REQUESTED';
export const PAYMENT_ACCOUNTS_DELETE_SUCCEEDED = 'kyc/payment/DELETE_SUCCEEDED';
export const PAYMENT_ACCOUNTS_DELETE_FAILED = 'kyc/payment/DELETE_FAILED';

export const PAYMENT_ACCOUNTS_EDIT_REQUESTED = 'kyc/payment/EDIT_REQUESTED';
export const PAYMENT_ACCOUNTS_EDIT_SUCCEEDED = 'kyc/payment/EDIT_SUCCEEDED';
export const PAYMENT_ACCOUNTS_EDIT_FAILED = 'kyc/payment/EDIT_FAILED';

export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_REQUESTED = 'kyc/payment/SET_AS_DEFAULT_REQUESTED';
export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_SUCCEEDED = 'kyc/payment/SET_AS_DEFAULT_SUCCEEDED';
export const PAYMENT_ACCOUNTS_SET_AS_DEFAULT_FAILED = 'kyc/payment/SET_AS_DEFAULT_FAILED';

export const PAYMENT_ACCOUNTS_VALIDATE_REQUESTED = 'kyc/payment/VALIDATE_REQUESTED';
export const PAYMENT_ACCOUNTS_VALIDATE_SUCCEEDED = 'kyc/payment/VALIDATE_SUCCEEDED';
export const PAYMENT_ACCOUNTS_VALIDATE_FAILED = 'kyc/payment/VALIDATE_FAILED';

export const PAYMENT_ACCOUNTS_FETCH_UPLOADED_SUPPORTING_DOCUMENT_FILE_REQUESTED = 'kyc/payment/FETCH_UPLOADED_SUPPORTED_DOC_REQUESTED';
export const PAYMENT_ACCOUNTS_FETCH_UPLOADED_SUPPORTING_DOCUMENT_FILE_SUCCEEDED = 'kyc/payment/FETCH_UPLOADED_SUPPORTED_DOC_SUCCEEDED';
export const PAYMENT_ACCOUNTS_FETCH_UPLOADED_SUPPORTING_DOCUMENT_FILE_FAILED = 'kyc/payment/FETCH_UPLOADED_SUPPORTED_DOC_FAILED';

export const ELM_USER_FETCH_REQUESTED = 'kyc/ELM_USER_FETCH_REQUESTED';
export const ELM_USER_FETCH_SUCCEEDED = 'kyc/ELM_USER_FETCH_SUCCEEDED';
export const ELM_USER_FETCH_FAILED = 'kyc/ELM_USER_FETCH_FAILED';
