export const MESSAGING_GET_MESSAGES_REQUESTED = 'MESSAGING_GET_MESSAGES_REQUESTED';
export const MESSAGING_GET_MESSAGES_SUCCEEDED = 'MESSAGING_GET_MESSAGES_SUCCEEDED';
export const MESSAGING_GET_MESSAGES_FAILED = 'MESSAGING_GET_MESSAGES_FAILED';

export const MESSAGING_SUBMIT_MESSAGES_REQUESTED = 'MESSAGING_SUBMIT_MESSAGES_REQUESTED';
export const MESSAGING_SUBMIT_MESSAGES_SUCCEEDED = 'MESSAGING_SUBMIT_MESSAGES_SUCCEEDED';
export const MESSAGING_SUBMIT_MESSAGES_FAILED = 'MESSAGING_SUBMIT_MESSAGES_FAILED';

export const OPEN_MESSAGE_SOCKET_REQUESTED = 'OPEN_MESSAGE_SOCKET_REQUESTED';
export const OPEN_MESSAGE_SOCKET_SUCCEEDED = 'OPEN_MESSAGE_SOCKET_SUCCEEDED';
export const OPEN_MESSAGE_SOCKET_FAILED = 'OPEN_MESSAGE_SOCKET_FAILED';
