export const DOCUMENT_LINK_FETCH_REQUESTED = 'DOCUMENT_LINK_FETCH_REQUESTED';
export const DOCUMENT_LINK_FETCH_SUCCEEDED = 'DOCUMENT_LINK_FETCH_SUCCEEDED';
export const DOCUMENT_LINK_FETCH_FAILED = 'DOCUMENT_LINK_FETCH_FAILED';

export const STATIC_FILE_REQUESTED = 'STATIC_FILE_REQUESTED';
export const STATIC_FILE_SUCCEEDED = 'STATIC_FILE_SUCCEEDED';
export const STATIC_FILE_FAILED = 'STATIC_FILE_FAILED';

export const READ_TABLE_CONFIG_REQUESTED = 'READ_TABLE_CONFIG_REQUESTED';
export const READ_TABLE_CONFIG_SUCCEEDED = 'READ_TABLE_CONFIG_SUCCEEDED';
export const READ_TABLE_CONFIG_FAILED = 'READ_TABLE_CONFIG_FAILED';

export const UPDATE_TABLE_CONFIG_REQUESTED = 'UPDATE_TABLE_CONFIG_REQUESTED';
export const UPDATE_TABLE_CONFIG_SUCCEEDED = 'UPDATE_TABLE_CONFIG_SUCCEEDED';
export const UPDATE_TABLE_CONFIG_FAILED = 'UPDATE_TABLE_CONFIG_FAILED';
