export const MODULE_FETCH_DATA_REQUESTED = "module/MODULE_FETCH_DATA_REQUESTED";
export const MODULE_FETCH_DATA_SUCCEEDED = "module/MODULE_FETCH_DATA_SUCCEEDED";
export const MODULE_FETCH_DATA_FAILED = "module/MODULE_FETCH_DATA_FAILED";

export const ADD_MODULE_ACCESS_REQUESTED = "module/ADD_MODULE_ACCESS_REQUESTED";
export const ADD_MODULE_ACCESS_SUCCEEDED = "module/ADD_MODULE_ACCESS_SUCCEEDED";
export const ADD_MODULE_ACCESS_FAILED = "module/ADD_MODULE_ACCESS_FAILED";

export const GRANT_MODULE_ACCESS_REQUESTED = "module/GRANT_MODULE_ACCESS_REQUESTED";
export const GRANT_MODULE_ACCESS_SUCCEEDED = "module/GRANT_MODULE_ACCESS_SUCCEEDED";
export const GRANT_MODULE_ACCESS_FAILED = "module/GRANT_MODULE_ACCESS_FAILED";

export const REVOKE_MODULE_ACCESS_REQUESTED = "module/REVOKE_MODULE_ACCESS_REQUESTED";
export const REVOKE_MODULE_ACCESS_SUCCEEDED = "module/REVOKE_MODULE_ACCESS_SUCCEEDED";
export const REVOKE_MODULE_ACCESS_FAILED = "module/REVOKE_MODULE_ACCESS_FAILED";

export const REQUEST_MODULE_ACCESS_REQUESTED = "module/REQUEST_MODULE_ACCESS_REQUESTED";
export const REQUEST_MODULE_ACCESS_SUCCEEDED = "module/REQUEST_MODULE_ACCESS_SUCCEEDED";
export const REQUEST_MODULE_ACCESS_FAILED = "module/REQUEST_MODULE_ACCESS_FAILED";
