export const NOTIFICATION_FETCH_ALL_REQUESTED = "NOTIFICATION_FETCH_ALL_REQUESTED";
export const NOTIFICATION_FETCH_ALL_SUCCEEDED = "NOTIFICATION_FETCH_ALL_SUCCEEDED";
export const NOTIFICATION_FETCH_ALL_FAILED = "NOTIFICATION_FETCH_ALL_FAILED";

export const NOTIFICATION_SET_READ_REQUESTED = "NOTIFICATION_SET_READ_REQUESTED";
export const NOTIFICATION_SET_READ_SUCCEEDED = "NOTIFICATION_SET_READ_SUCCEEDED";
export const NOTIFICATION_SET_READ_FAILED = "NOTIFICATION_SET_READ_FAILED";

export const OPEN_NOTIFICATION_SOCKET_REQUESTED = "OPEN_NOTIFICATION_SOCKET_REQUESTED";
export const OPEN_NOTIFICATION_SOCKET_SUCCEEDED = "OPEN_NOTIFICATION_SOCKET_SUCCEEDED";
export const OPEN_NOTIFICATION_SOCKET_FAILED = "OPEN_NOTIFICATION_SOCKET_FAILED";
