export const ONBOARDING_SIGNUP_REQUESTED = "onboarding/ONBOARDING_SIGNUP_REQUESTED";
export const ONBOARDING_SIGNUP_SUCCEEDED = "onboarding/ONBOARDING_SIGNUP_SUCCEEDED";
export const ONBOARDING_SIGNUP_FAILED = "onboarding/ONBOARDING_SIGNUP_FAILED";

export const ONBOARDING_DROPDOWN_REQUESTED = "onboarding/DROPDOWN_REQUESTED";
export const ONBOARDING_DROPDOWN_SUCCEEDED = "onboarding/DROPDOWN_SUCCEEDED";
export const ONBOARDING_DROPDOWN_FAILED = "onboarding/DROPDOWN_FAILED";

export const ONBOARDING_INVITE_USER_REQUESTED = "onboarding/INVITE_USER_REQUESTED";
export const ONBOARDING_INVITE_USER_SUCCEEDED = "onboarding/INVITE_USER_SUCCEEDED";
export const ONBOARDING_INVITE_USER_FAILED = "onboarding/INVITE_USER_FAILED";

export const ONBOARDING_INVITE_PUBLIC_REQUESTED = "onboarding/INVITE_PUBLIC_REQUESTED";
export const ONBOARDING_INVITE_PUBLIC_SUCCEEDED = "onboarding/INVITE_PUBLIC_SUCCEEDED";
export const ONBOARDING_INVITE_PUBLIC_FAILED = "onboarding/INVITE_PUBLIC_FAILED";

export const ONBOARDING_FETCH_RM_VISITORS_REQUESTED = "onboarding/FETCH_RM_VISITORS_REQUESTED";
export const ONBOARDING_FETCH_RM_VISITORS_SUCCEEDED = "onboarding/FETCH_RM_VISITORS_SUCCEEDED";
export const ONBOARDING_FETCH_RM_VISITORS_FAILED = "onboarding/FETCH_RM_VISITORS_FAILED";

export const ONBOARDING_FETCH_RM_REQUESTED = "onboarding/FETCH_RM_REQUESTED";
export const ONBOARDING_FETCH_RM_SUCCEEDED = "onboarding/FETCH_RM_SUCCEEDED";
export const ONBOARDING_FETCH_RM_FAILED = "onboarding/FETCH_RM_FAILED";

export const ONBOARDING_PROCESS_VISITOR_REQUESTED = "onboarding/PROCESS_VISITOR_REQUESTED";
export const ONBOARDING_PROCESS_VISITOR_SUCCEEDED = "onboarding/PROCESS_VISITOR_SUCCEEDED";
export const ONBOARDING_PROCESS_VISITOR_FAILED = "onboarding/PROCESS_VISITOR_FAILED";

export const ONBOARDING_FETCH_USER_INFO_REQUESTED = "onboarding/FETCH_USER_INFO_REQUESTED";
export const ONBOARDING_FETCH_USER_INFO_SUCCEEDED = "onboarding/FETCH_USER_INFO_SUCCEEDED";
export const ONBOARDING_FETCH_USER_INFO_FAILED = "onboarding/FETCH_USER_INFO_FAILED";

export const ONBOARDING_APPROVE_USER_REQUESTED = "onboarding/APPROVE_USER_REQUESTED";
export const ONBOARDING_APPROVE_USER_SUCCEEDED = "onboarding/APPROVE_USER_SUCCEEDED";
export const ONBOARDING_APPROVE_USER_FAILED = "onboarding/APPROVE_USER_FAILED";

export const ONBOARDING_ASSIGN_ADMIN_REQUESTED = "onboarding/ASSIGN_ADMIN_REQUESTED";
export const ONBOARDING_ASSIGN_ADMIN_SUCCEEDED = "onboarding/ASSIGN_ADMIN_SUCCEEDED";
export const ONBOARDING_ASSIGN_ADMIN_FAILED = "onboarding/ASSIGN_ADMIN_FAILED";

export const ONBOARDING_RESEND_ONBOARDING_EMAIL_REQUESTED =
  "onboarding/RESEND_ONBOARDING_EMAIL_REQUESTED";
export const ONBOARDING_RESEND_ONBOARDING_EMAIL_SUCCEEDED =
  "onboarding/RESEND_ONBOARDING_EMAIL_SUCCEEDED";
export const ONBOARDING_RESEND_ONBOARDING_EMAIL_FAILED =
  "onboarding/RESEND_ONBOARDING_EMAIL_FAILED";
