export const PAYMENT_DETAILS_REQUESTED = 'payments/PAYMENT_DETAILS_REQUESTED';
export const PAYMENT_DETAILS_SUCCEEDED = 'payments/PAYMENT_DETAILS_SUCCEEDED';
export const PAYMENT_DETAILS_FAILED = 'payments/PAYMENT_DETAILS_FAILED';

export const BLOTTER_READ_REQUESTED = 'payments/BLOTTER_READ_REQUESTED';
export const BLOTTER_READ_SUCCEEDED = 'payments/BLOTTER_READ_SUCCEEDED';
export const BLOTTER_READ_FAILED = 'payments/BLOTTER_READ_FAILED';

export const BLOTTER_UPDATE_REQUESTED = 'payments/BLOTTER_UPDATE_REQUESTED';
export const BLOTTER_UPDATE_SUCCEEDED = 'payments/BLOTTER_UPDATE_SUCCEEDED';
export const BLOTTER_UPDATE_FAILED = 'payments/BLOTTER_UPDATE_FAILED';

export const BLOTTER_CREATE_REQUESTED = 'payments/BLOTTER_CREATE_REQUESTED';
export const BLOTTER_CREATE_SUCCEEDED = 'payments/BLOTTER_CREATE_SUCCEEDED';
export const BLOTTER_CREATE_FAILED = 'payments/BLOTTER_CREATE_FAILED';

export const BLOTTER_DELETE_REQUESTED = 'payments/BLOTTER_DELETE_REQUESTED';
export const BLOTTER_DELETE_SUCCEEDED = 'payments/BLOTTER_DELETE_SUCCEEDED';
export const BLOTTER_DELETE_FAILED = 'payments/BLOTTER_DELETE_FAILED';

export const READ_DROPDOWN_REQUESTED = 'payments/READ_DROPDOWN_REQUESTED';
export const READ_DROPDOWN_SUCCEEDED = 'payments/READ_DROPDOWN_SUCCEEDED';
export const READ_DROPDOWN_FAILED = 'payments/READ_DROPDOWN_FAILED';

export const TRADE_SETTLEMENT_REQUESTED = 'payments/TRADE_SETTLEMENT_REQUESTED';
export const TRADE_SETTLEMENT_SUCCEEDED = 'payments/TRADE_SETTLEMENT_SUCCEEDED';
export const TRADE_SETTLEMENT_FAILED = 'payments/TRADE_SETTLEMENT_FAILED';

export const CLIENT_ACCOUNT_UPDATE_REQUESTED = 'payments/CLIENT_ACCOUNT_UPDATE_REQUESTED';
export const CLIENT_ACCOUNT_UPDATE_SUCCEEDED = 'payments/CLIENT_ACCOUNT_UPDATE_SUCCEEDED';
export const CLIENT_ACCOUNT_UPDATE_FAILED = 'payments/CLIENT_ACCOUNT_UPDATE_FAILED';

export const TRADE_APPROVAL_REQUESTED = 'payments/TRADE_APPROVAL_REQUESTED';
export const TRADE_APPROVAL_SUCCEEDED = 'payments/TRADE_APPROVAL_SUCCEEDED';
export const TRADE_APPROVAL_FAILED = 'payments/TRADE_APPROVAL_FAILED';

export const RAISE_SETTLEMENT_INSTRUCTION_REQUESTED = 'payments/RAISE_SETTLEMENT_INSTRUCTION_REQUESTED';
export const RAISE_SETTLEMENT_INSTRUCTION_SUCCEEDED = 'payments/RAISE_SETTLEMENT_INSTRUCTION_SUCCEEDED';
export const RAISE_SETTLEMENT_INSTRUCTION_FAILED = 'payments/RAISE_SETTLEMENT_INSTRUCTION_FAILED';

export const RAISE_BULK_SETTLEMENT_INSTRUCTIONS_REQUESTED = 'payments/RAISE_BULK_SETTLEMENT_INSTRUCTIONS_REQUESTED';
export const RAISE_BULK_SETTLEMENT_INSTRUCTIONS_SUCCEEDED = 'payments/RAISE_BULK_SETTLEMENT_INSTRUCTIONS_SUCCEEDED';
export const RAISE_BULK_SETTLEMENT_INSTRUCTIONS_FAILED = 'payments/RAISE_BULK_SETTLEMENT_INSTRUCTIONS_FAILED';

export const UPDATE_SETTLEMENT_INSTRUCTION_REQUESTED = 'payments/UPDATE_SETTLEMENT_INSTRUCTION_REQUESTED';
export const UPDATE_SETTLEMENT_INSTRUCTION_SUCCEEDED = 'payments/UPDATE_SETTLEMENT_INSTRUCTION_SUCCEEDED';
export const UPDATE_SETTLEMENT_INSTRUCTION_FAILED = 'payments/UPDATE_SETTLEMENT_INSTRUCTION_FAILED';

export const DELETE_SETTLEMENT_INSTRUCTION_REQUESTED = 'payments/DELETE_SETTLEMENT_INSTRUCTION_REQUESTED';
export const DELETE_SETTLEMENT_INSTRUCTION_SUCCEEDED = 'payments/DELETE_SETTLEMENT_INSTRUCTION_SUCCEEDED';
export const DELETE_SETTLEMENT_INSTRUCTION_FAILED = 'payments/DELETE_SETTLEMENT_INSTRUCTION_FAILED';

export const SETTLE_SETTLEMENT_INSTRUCTION_REQUESTED = 'payments/SETTLE_SETTLEMENT_INSTRUCTION_REQUESTED';
export const SETTLE_SETTLEMENT_INSTRUCTION_SUCCEEDED = 'payments/SETTLE_SETTLEMENT_INSTRUCTION_SUCCEEDED';
export const SETTLE_SETTLEMENT_INSTRUCTION_FAILED = 'payments/SETTLE_SETTLEMENT_INSTRUCTION_FAILED';

export const FETCH_PAYMENTS_LIST_REQUESTED = 'payments/FETCH_PAYMENTS_LIST_REQUESTED';
export const FETCH_PAYMENTS_LIST_SUCCEEDED = 'payments/FETCH_PAYMENTS_LIST_SUCCEEDED';
export const FETCH_PAYMENTS_LIST_FAILED = 'payments/FETCH_PAYMENTS_LIST_FAILED';

export const CHANGE_SETTLEMENT_INSTRUCTION_STATUS_REQUESTED = 'payments/CHANGE_SETTLEMENT_INSTRUCTION_STATUS_REQUESTED';
export const CHANGE_SETTLEMENT_INSTRUCTION_STATUS_SUCCEEDED = 'payments/CHANGE_SETTLEMENT_INSTRUCTION_STATUS_SUCCEEDED';
export const CHANGE_SETTLEMENT_INSTRUCTION_STATUS_FAILED = 'payments/CHANGE_SETTLEMENT_INSTRUCTION_STATUS_FAILED';

export const FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_REQUESTED = 'payments/FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_REQUESTED';
export const FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_SUCCEEDED = 'payments/FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_SUCCEEDED';
export const FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_FAILED = 'payments/FETCH_SETTLEMENT_INSTRUCTION_AUDIT_DATA_FAILED';

export const RESET_SETTLEMENT_INSTRUCTION_AUDIT_DATA_REQUESTED = 'payments/RESET_SETTLEMENT_INSTRUCTION_AUDIT_DATA_REQUESTED';
