export const CREATE_QUOTE_REQUESTED = "CREATE_QUOTE_REQUESTED";
export const CREATE_QUOTE_SUCCEEDED = "CREATE_QUOTE_SUCCEEDED";
export const CREATE_QUOTE_FAILED = "CREATE_QUOTE_FAILED";

export const READ_QUOTE_REQUESTED = "READ_QUOTE_REQUESTED";
export const READ_QUOTE_SUCCEEDED = "READ_QUOTE_SUCCEEDED";
export const READ_QUOTE_FAILED = "READ_QUOTE_FAILED";

export const UPDATE_QUOTE_REQUESTED = "UPDATE_QUOTE_REQUESTED";
export const UPDATE_QUOTE_SUCCEEDED = "UPDATE_QUOTE_SUCCEEDED";
export const UPDATE_QUOTE_FAILED = "UPDATE_QUOTE_FAILED";

export const DELETE_QUOTE_REQUESTED = "DELETE_QUOTE_REQUESTED";
export const DELETE_QUOTE_SUCCEEDED = "DELETE_QUOTE_SUCCEEDED";
export const DELETE_QUOTE_FAILED = "DELETE_QUOTE_FAILED";
