export const FETCH_CASH_ACCOUNTS_REQUESTED = "reports/FETCH_CASH_ACCOUNTS_REQUESTED";
export const FETCH_CASH_ACCOUNTS_SUCCEEDED = "reports/FETCH_CASH_ACCOUNTS_SUCCEEDED";
export const FETCH_CASH_ACCOUNTS_FAILED = "reports/FETCH_CASH_ACCOUNTS_FAILED";

export const FETCH_CASH_TRANSACTIONS_REQUESTED = "reports/FETCH_CASH_TRANSACTIONS_REQUESTED";
export const FETCH_CASH_TRANSACTIONS_SUCCEEDED = "reports/FETCH_CASH_TRANSACTIONS_SUCCEEDED";
export const FETCH_CASH_TRANSACTIONS_FAILED = "reports/FETCH_CASH_TRANSACTIONS_FAILED";

export const RESET_CASH_TRANSACTIONS = "reports/RESET_CASH_TRANSACTIONS";

export const FETCH_CASH_BALANCES_REQUESTED = "reports/FETCH_CASH_BALANCES_REQUESTED";
export const FETCH_CASH_BALANCES_SUCCEEDED = "reports/FETCH_CASH_BALANCES_SUCCEEDED";
export const FETCH_CASH_BALANCES_FAILED = "reports/FETCH_CASH_BALANCES_FAILED";

export const RESET_CASH_BALANCES = "reports/RESET_CASH_BALANCES";

export const FETCH_SECURITIES_ACCOUNTS_REQUESTED = "reports/FETCH_SECURITIES_ACCOUNTS_REQUESTED";
export const FETCH_SECURITIES_ACCOUNTS_SUCCEEDED = "reports/FETCH_SECURITIES_ACCOUNTS_SUCCEEDED";
export const FETCH_SECURITIES_ACCOUNTS_FAILED = "reports/FETCH_SECURITIES_ACCOUNTS_FAILED";

export const FETCH_SECURITIES_TRANSACTIONS_REQUESTED =
  "reports/FETCH_SECURITIES_TRANSACTIONS_REQUESTED";
export const FETCH_SECURITIES_TRANSACTIONS_SUCCEEDED =
  "reports/FETCH_SECURITIES_TRANSACTIONS_SUCCEEDED";
export const FETCH_SECURITIES_TRANSACTIONS_FAILED = "reports/FETCH_SECURITIES_TRANSACTIONS_FAILED";

export const RESET_SECURITIES_TRANSACTIONS = "reports/RESET_SECURITIES_TRANSACTIONS";

export const FETCH_SECURITIES_HOLDINGS_REQUESTED = "reports/FETCH_SECURITIES_HOLDINGS_REQUESTED";
export const FETCH_SECURITIES_HOLDINGS_SUCCEEDED = "reports/FETCH_SECURITIES_HOLDINGS_SUCCEEDED";
export const FETCH_SECURITIES_HOLDINGS_FAILED = "reports/FETCH_SECURITIES_HOLDINGS_FAILED";

export const FETCH_TRADE_DATED_SECURITIES_HOLDINGS_REQUESTED =
  "reports/FETCH_TRADE_DATED_SECURITIES_HOLDINGS_REQUESTED";
export const FETCH_TRADE_DATED_SECURITIES_HOLDINGS_SUCCEEDED =
  "reports/FETCH_TRADE_DATED_SECURITIES_HOLDINGS_SUCCEEDED";
export const FETCH_TRADE_DATED_SECURITIES_HOLDINGS_FAILED =
  "reports/FETCH_TRADE_DATED_SECURITIES_HOLDINGS_FAILED";

export const RESET_SECURITIES_HOLDINGS = "reports/RESET_SECURITIES_HOLDINGS";

export const FETCH_REFERENCE_DATA_REQUESTED = "reports/FETCH_REFERENCE_DATA_REQUESTED";
export const FETCH_REFERENCE_DATA_SUCCEEDED = "reports/FETCH_REFERENCE_DATA_SUCCEEDED";
export const FETCH_REFERENCE_DATA_FAILED = "reports/FETCH_REFERENCE_DATA_FAILED";
