export const SECURITIES_SERVICES_FILE_UPLOAD_SUCCEEDED =
  "securities_services/FILE_UPLOAD_SUCCEEDED";
export const SECURITIES_SERVICES_FILE_UPLOAD_REQUESTED =
  "securities_services/FILE_UPLOAD_REQUESTED";
export const SECURITIES_SERVICES_FILE_UPLOAD_FAILED = "securities_services/FILE_UPLOAD_FAILED";

export const SECURITIES_SERVICES_FILE_FETCH_SUCCEEDED = "securities_services/FILE_FETCH_SUCCEEDED";
export const SECURITIES_SERVICES_FILE_FETCH_REQUESTED = "securities_services/FILE_FETCH_REQUESTED";
export const SECURITIES_SERVICES_FILE_FETCH_FAILED = "securities_services/FILE_FETCH_FAILED";

export const SECURITIES_SERVICES_RESET_FILES_STATE = "securities_services/RESET_FILES_STATE";
