export const SERVICE_PROVIDER_LIST_REQUESTED = 'serviceProviders/LIST_REQUESTED';
export const SERVICE_PROVIDER_LIST_SUCCEEDED = 'serviceProviders/LIST_SUCCEEDED';
export const SERVICE_PROVIDER_LIST_FAILED = 'serviceProviders/LIST_FAILED';

export const SERVICE_PROVIDER_ENGAGE_LA_REQUESTED = 'serviceProviders/ENGAGE_LA_REQUESTED';
export const SERVICE_PROVIDER_ENGAGE_LA_SUCCEEDED = 'serviceProviders/ENGAGE_LA_SUCCEEDED';
export const SERVICE_PROVIDER_ENGAGE_LA_FAILED = 'serviceProviders/ENGAGE_LA_FAILED';

export const SERVICE_PROVIDER_ENGAGE_SP_REQUESTED = 'serviceProviders/ENGAGE_SP_REQUESTED';
export const SERVICE_PROVIDER_ENGAGE_SP_SUCCEEDED = 'serviceProviders/ENGAGE_SP_SUCCEEDED';
export const SERVICE_PROVIDER_ENGAGE_SP_FAILED = 'serviceProviders/ENGAGE_SP_FAILED';
