export const READ_DROPDOWN_REQUESTED = 'support/READ_DROPDOWN_REQUESTED';
export const READ_DROPDOWN_SUCCEEDED = 'support/READ_DROPDOWN_SUCCEEDED';
export const READ_DROPDOWN_FAILED = 'support/READ_DROPDOWN_FAILED';

export const FETCH_TFA_TICKETS_REQUESTED = 'support/FETCH_TFA_TICKETS_REQUESTED';
export const FETCH_TFA_TICKETS_SUCCEEDED = 'support/FETCH_TFA_TICKETS_SUCCEEDED';
export const FETCH_TFA_TICKETS_FAILED = 'support/FETCH_TFA_TICKETS_FAILED';

export const UPLOAD_TFA_VERIFICATION_DOCUMENT_REQUESTED = 'support/UPLOAD_TFA_VERIFICATION_DOCUMENT_REQUESTED';
export const UPLOAD_TFA_VERIFICATION_DOCUMENT_SUCCEEDED = 'support/UPLOAD_TFA_VERIFICATION_DOCUMENT_SUCCEEDED';
export const UPLOAD_TFA_VERIFICATION_DOCUMENT_FAILED = 'support/UPLOAD_TFA_VERIFICATION_DOCUMENT_FAILED';

export const TFA_VERIFICATION_DOCUMENT_FETCH_REQUESTED = 'support/TFA_VERIFICATION_DOCUMENT_FETCH_REQUESTED';
export const TFA_VERIFICATION_DOCUMENT_FETCH_SUCCEEDED = 'support/TFA_VERIFICATION_DOCUMENT_FETCH_SUCCEEDED';
export const TFA_VERIFICATION_DOCUMENT_FETCH_FAILED = 'support/TFA_VERIFICATION_DOCUMENT_FETCH_FAILED';

export const TFA_TICKET_CREATE_REQUESTED = 'support/TFA_TICKET_CREATE_REQUESTED';
export const TFA_TICKET_CREATE_SUCCEEDED = 'support/TFA_TICKET_CREATE_SUCCEEDED';
export const TFA_TICKET_CREATE_FAILED = 'support/TFA_TICKET_CREATE_FAILED';

export const TFA_TICKET_DELETE_REQUESTED = 'support/TFA_TICKET_DELETE_REQUESTED';
export const TFA_TICKET_DELETE_SUCCEEDED = 'support/TFA_TICKET_DELETE_SUCCEEDED';
export const TFA_TICKET_DELETE_FAILED = 'support/TFA_TICKET_DELETE_FAILED';

export const TFA_TICKET_APPROVE_REQUESTED = 'support/TFA_TICKET_APPROVE_REQUESTED';
export const TFA_TICKET_APPROVE_SUCCEEDED = 'support/TFA_TICKET_APPROVE_SUCCEEDED';
export const TFA_TICKET_APPROVE_FAILED = 'support/TFA_TICKET_APPROVE_FAILED';
