export const TNC_DATA_UPDATE_REQUESTED = 'tnc/DATA_UPDATE_REQUESTED';
export const TNC_DATA_UPDATE_SUCCEEDED = 'tnc/DATA_UPDATE_SUCCEEDED';
export const TNC_DATA_UPDATE_FAILED = 'tnc/DATA_UPDATE_FAILED';

export const TNC_DATA_FETCH_REQUESTED = 'tnc/DATA_FETCH_REQUESTED';
export const TNC_DATA_FETCH_SUCCEEDED = 'tnc/DATA_FETCH_SUCCEEDED';
export const TNC_DATA_FETCH_FAILED = 'tnc/DATA_FETCH_FAILED';

export const TNC_STATUS_FETCH_REQUESTED = 'tnc/STATUS_FETCH_REQUESTED';
export const TNC_STATUS_FETCH_SUCCEEDED = 'tnc/STATUS_FETCH_SUCCEEDED';
export const TNC_STATUS_FETCH_FAILED = 'tnc/STATUS_FETCH_FAILED';

export const TNC_ACCEPTANCE_REQUESTED = 'tnc/ACCEPTANCE_REQUESTED';
export const TNC_ACCEPTANCE_SUCCEEDED = 'tnc/ACCEPTANCE_SUCCEEDED';
export const TNC_ACCEPTANCE_FAILED = 'tnc/ACCEPTANCE_FAILED';
