export const UPDATE_USER_ACCOUNT_STATUS_REQUESTED = 'entities/UPDATE_USER_ACCOUNT_STATUS_REQUESTED';
export const UPDATE_USER_ACCOUNT_STATUS_SUCCEEDED = 'entities/UPDATE_USER_ACCOUNT_STATUS_SUCCEEDED';
export const UPDATE_USER_ACCOUNT_STATUS_FAILED = 'entities/UPDATE_USER_ACCOUNT_STATUS_FAILED';
