# !REMINDER: There's no way to DRY UP those rules as array merging is not supported by GitLab CI/CD parser.

.client_auth_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/client-authentication/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.client_primaries_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/client-primaries/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.client_secondaries_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/client-secondaries/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.client_accounts_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/client-accounts/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

# .silver-internal_build_rules_develop:
#   rules:
#     - if: $CI_COMMIT_BRANCH == "develop"
#       when: always
#       changes:
#         paths:
#           - apps/silver-internal/**/*
#           - .gitlab-ci.yml
#           - .gitlab/**/*
#           - Dockerfile
#           - package-lock.json
#           - package.json
#           - packages/**/*
#           - .env.production
#

.silver-admin_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/silver-administration/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.silver-auth_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/silver-authentication/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.silver-dataroom_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/silver-dataroom/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production

.silver-onboarding_build_rules_develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
      changes:
        paths:
          - apps/silver-onboarding/**/*
          - .gitlab-ci.yml
          - .gitlab/**/*
          - Dockerfile
          - docker-compose.prod.template.yml
          - package-lock.json
          - package.json
          - packages/**/*
          - .env.production
